### ISSUE TITLE
BasicNetwork.performRequest: Unexpected response code 500 or 503

### ISSUE THREAD

**Issue by KimiChiu** [google/volley#104]
E/Volley: [615] BasicNetwork.performRequest: Unexpected response code 500(or 503) for https://imgur-apiv3.p.mashape.com/3/image E/ImgurUploadTask: Failed to upload image file. json = com.android.volley.ServerError at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:163) at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)

The error rate raised up to 10% to 20% after I changed the library from mcxiaoke/android-volley to google/volley.
Same thing happens to Google UrlShortener API. And the error rate is 10% to 20% too.
Is this the API's problem or the Volley's?

   ```
             try {
                JsonObjectRequest jsonRequest = new JsonObjectRequest(Request.Method.POST, service, new JSONObject(json),
                        new Response.Listener<JSONObject>() {
                            @Override
                            public void onResponse(JSONObject response) {
                                VolleyRequest.this.onResponse( response.toString(), callback );
                            }
                        },
                        new Response.ErrorListener() {
                            @Override
                            public void onErrorResponse(VolleyError error) {
                                VolleyRequest.this.onErrorResponse(error, callback);
                            }
                        }){
                    /**
                     * Passing some request headers
                     * */
                    @Override
                    public Map<String, String> getHeaders() throws AuthFailureError {
                        return VolleyRequest.this.getHeaders();
                    }
                };

                jsonRequest.setShouldCache(false);
                Volley.newRequestQueue(context).add(jsonRequest).setRetryPolicy(new DefaultRetryPolicy( TIMEOUT,
                    DefaultRetryPolicy.DEFAULT_MAX_RETRIES,
                    DefaultRetryPolicy.DEFAULT_BACKOFF_MULT ) );
            } catch (JSONException e) {
                Timber.e(e, "Failed to convert json to JSONObject.");
                callback.onFailed( longUrl, ERROR_JSON_OBJECT_CONVERT, "物件建立失敗" );
            }
```

**Comment by jpd236** [comment]
A server transiently returning 500s is presumably an issue with the server, or you're doing something like trying more frequently. Perhaps the two versions of Volley handle retries differently. But I don't really know anything about the changes in the other fork so I don't know what can be done here. If you can concretely identify what is happening differently in how the requests are being issued then perhaps we can look at it more.

**Comment by myralyngarcia** [comment]
hi I am having the same issue, MY app is sending a POST request to Heroku and my app is logging this, please help (when I send same request using postman it is successful).

01-30 22:46:23.403 29531-29581/com.example.myralyn.smack E/Volley: [1072] BasicNetwork.performRequest: Unexpected response code 500 for https://chattymyra.herokuapp.com/v1/account/register
01-30 22:46:23.406 29531-29531/com.example.myralyn.smack D/ERROR: could not register user: com.android.volley.ServerError
01-30 22:46:23.407 29531-29531/com.example.myralyn.smack I/System.out: failed to register user

**Comment by softwrengr** [comment]
hello 
I also facing the same issue when I am trying to hit the APIs frequently its occur.

**Comment by NiranjanNlc** [comment]
E/Volley: [1100] BasicNetwork.performRequest: Unexpected response code 500 for http://niranjanlamichhane.com/SmartGovernance/includes/Complains.php
 ocurred

**Comment by kishorpatel85** [comment]
@NiranjanNlc solved the issue?

**Comment by sneogi-cci** [comment]
Hello, Any update on this issue? I am facing the same issue when Calling multiple API calls. Some gives response and some fail with 500 error.

**Comment by sherazmahar** [comment]
hi I am having the same issue, MY app is sending a POST request for user registration to localhost server using volley and my app is logging this, please help (when I send same request using postman it is successful).

BasicNetwork.performRequest: Unexpected response code 403 for

**Comment by sherazmahar** [comment]
I am having the same issue, MY app is sending a POST request to Server and my app is logging this, (when I send same request using postman it is successful).

01-30 22:46:23.403 29531-29581/com.example.gpt. E/Volley: [1072] BasicNetwork.performRequest: Unexpected response code 500 for https://stage.global-patienttransfer.com/member/registration
01-30 22:46:23.406 29531-29531/com.example.gpt D/ERROR: could not register user:

**Comment by maheshts** [comment]
any issue found?

**Comment by jpd236** [comment]
I think the fact that this issue remains open for comment is confusing people, so I'm going to lock it for further comments.

I've added an FAQ regarding this error message at: https://github.com/google/volley/wiki/Frequently-Asked-Questions#im-getting-this-error-basicnetworkperformrequest-unexpected-response-code

Please take a look there if you are seeing this error code before reporting an issue in this tracker. The most likely scenario is that the issue is with your server or how you're assembling the request on the client, and not anything with Volley itself.
