### ISSUE TITLE
NoConnectionError: java.io.IOException: unexpected end of stream on com.android.okhttp.Address

### ISSUE THREAD

**Issue by devganiyahitesh1** [google/volley#111]
I am getting this error sometime only. Not able to find any case where this is happening. 

> 10-16 10:19:05.638 3937-3937/com.xx W/System.err: com.android.volley.NoConnectionError: java.io.IOException: unexpected end of stream on com.android.okhttp.Address@c80ce314
10-16 10:19:05.638 3937-3937/com.xx W/System.err:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:151)
10-16 10:19:05.638 3937-3937/com.xx W/System.err:     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
10-16 10:19:05.638 3937-3937/com.xx W/System.err: Caused by: java.io.IOException: unexpected end of stream on com.android.okhttp.Address@c80ce314
10-16 10:19:05.638 3937-3937/com.xx W/System.err:     at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
10-16 10:19:05.638 3937-3937/com.xx W/System.err:     at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
10-16 10:19:05.638 3937-3937/com.xx W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
10-16 10:19:05.638 3937-3937/com.xx W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
10-16 10:19:05.638 3937-3937/com.xx W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
10-16 10:19:05.638 3937-3937/com.xx W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
10-16 10:19:05.638 3937-3937/com.xx W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
10-16 10:19:05.638 3937-3937/com.xx W/System.err:     at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:110)
10-16 10:19:05.638 3937-3937/com.xx W/System.err:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
10-16 10:19:05.638 3937-3937/com.xx W/System.err: ... 1 more
10-16 10:19:05.638 3937-3937/com.xx W/System.err: Caused by: java.io.EOFException: \n not found: size=0 content=...
10-16 10:19:05.638 3937-3937/com.xx W/System.err:     at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
10-16 10:19:05.638 3937-3937/com.xx W/System.err:     at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
10-16 10:19:05.638 3937-3937/com.xx W/System.err: ... 9 more

**Comment by jpd236** [comment]
This seems unlikely to be a Volley issue rather than an issue with HttpUrlConnection on the device you're testing with. I'd expect that if it reproduces with any consistency, you'd also see it when using HttpUrlConnection directly rather than with Volley.

From a quick glance at the stack trace, it seems like https://github.com/square/okhttp/issues/1517 is a relevant discussion as OkHttp is being used to implement HttpUrlConnection's interface on this device. It seems generally likely to be a server issue. Perhaps you can add more retries to work around it, or use an alternative HTTP stack with Volley.

**Comment by waleedmakarem** [comment]
I am having same issue. Did anyone manage to solve
Thanks..
