### ISSUE TITLE
Compatibility with SDK 23

### ISSUE THREAD

**Issue by vivekkartha** [google/volley#133]
Is there a version of Volley that uses UrlConnection? HttpClient is no longer supported by Android.

**Comment by jpd236** [comment]
All versions of Volley support an HttpUrlConnection-based stack (HurlStack). It is used by default on API 9+ devices. You can still build any version of Volley on SDK 23+ by specifying that the org.apache.http.legacy library should be used. However, this requirement was lifted if you upgrade to Volley 1.1.0, although some changes may be needed to your codebase. More details here: https://github.com/google/volley/wiki/Migrating-from-Apache-HTTP
