### ISSUE TITLE
Volley not working on jelly bean or lower 

### ISSUE THREAD

**Issue by bironader** [google/volley#134]
public void postRequest(String url, JSONObject body) {

        JsonObjectRequest postReq = new JsonObjectRequest(Request.Method.POST, url, body, new Response.Listener<JSONObject>() {

            @Override
            public void onResponse(JSONObject response) {
                try {
                    volleyCallback.onSuccess(response);
                    Log.d("response", response.toString());
                } catch (JSONException e) {
                    e.printStackTrace();
                }

            }

        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                volleyCallback.onError(error);

            }

        });
        postReq.setShouldCache(false);
        App.getInstance().addToRequestQueue(postReq);

    }

the problem I get null pointer exception on VolleyError error and when I try the same previous code on marshmello Its work fine

**Comment by jpd236** [comment]
Do you have the full stack trace of the failure? (And ideally a fully functional sample app that we could run on emulator to reproduce it?) Does this happen on emulator or only on a particular device?

**Comment by bironader** [comment]
@jpd236 The problem was in https protocols configuration from backend server only open Tlsv1.2 which is not supported by some low android APIS

SSL protocols supported by devices lower than KitKat "TLSv1" and "SSlv3"

SSL protocols supported by devices higher than KitKat "TLSv1", "TLsv1.1" and "TLSv1.2" 

Thanks for your concern.

**Comment by jpd236** [comment]
Thanks - this is the same issue as #77.
