### ISSUE TITLE
can someone please help regarding 500 response code when Volley sends post request to Heroku

### ISSUE THREAD

**Issue by myralyngarcia** [google/volley#142]
My app sending post request to heroku and in heroku the 500 response is not descriptive.
Below is from logcat from android studio when my app tries to send the POST request.

01-30 22:46:23.403 29531-29581/com.example.myralyn.smack E/Volley: [1072] BasicNetwork.performRequest: Unexpected response code 500 for https://chattymyra.herokuapp.com/v1/account/register
01-30 22:46:23.406 29531-29531/com.example.myralyn.smack D/ERROR: could not register user: com.android.volley.ServerError
01-30 22:46:23.407 29531-29531/com.example.myralyn.smack I/System.out: failed to register user.

For completeness here is my app code:
fun registerUser(context: Context, email: String, password: String, completion: (Boolean)-> Unit){
        val url = URL_REGISTER
        val jsonBody = JSONObject()
        jsonBody.put("email", email)
        jsonBody.put("password", password)
        //convert request body to string so we can convert to byteArray for Volley
        val requestBody = jsonBody.toString()

        //now create the registerRequest object
        val registerRequest = object : StringRequest(Method.POST, url, Response.Listener { response ->
            println(response)
            completion(true)
        }, Response.ErrorListener { error ->
            Log.d("ERROR", "could not register user: $error")
            completion(false)

        }){
            override fun getBodyContentType(): String {
                return "application/json: charset=utf-8"
                //return "Content-Type: application/json"
            }

            override fun getBody(): ByteArray {
                return requestBody.toByteArray()
            }
        }
        //put reqister request in the queue in this context
        Volley.newRequestQueue(context).add(registerRequest)
    }

**Comment by jpd236** [comment]
It's unlikely that a server-side error code is a bug in Volley. I'd suggest another general help forum for Volley questions, such as volley-users@googlegroups.com, or StackOverflow, as this is Volley's bug tracker.

If one library is working and the other isn't, that would imply the request being sent to the server is unlikely to be exactly the same, so I'd check the server-side logs to see what's different about them. You can also get more details about the error by inspecting the networkResponse field within ServerError which is the raw network response from the server.

**Comment by matt-matt1** [comment]
While creating my app, I would make several requests - using volley.  A few of theme would throw an error - 500.
Then I replaced the queue code (like you have in the last line).  With the code for MySingleton class:

	RequestQueue requestQueue = MySingleton.getInstance(getAppContext()).getRequestQueue();
	MySingleton.getInstance(context).addToRequestQueue(request);

Then no more 500s!

**Comment by Royanid** [comment]
can u explain detailly

**Comment by mindcheck** [comment]
Its because of duplicate records. please delete it from db.
