### ISSUE TITLE
NegativeArraySizeException

### ISSUE THREAD

**Issue by scholt** [google/volley#144]
The following Exception popped up in Crashlytics (so unfortunately I can't give very much more Information). This happened with 1.1.0 (I saw from other issues that there was something related to this which should have been fixed in 1.1.0?)

`Fatal Exception: java.lang.NegativeArraySizeException: -836
       at com.android.volley.toolbox.DiskBasedCache.get(Unknown Source)
       at com.android.volley.toolbox.DiskBasedCache.get(Unknown Source)
       at com.android.volley.CacheDispatcher.run(Unknown Source)`

Is there anything I can do?

**Comment by joebowbeer** [comment]
Probably a dup of #127 

You want to specify a 1.1.1-SNAPSHOT that contains #129 
See instructions at end of #127

**Comment by jpd236** [comment]
Agreed, thanks @joebowbeer. Can't confirm for sure since the source lines are unknown (I guess proguard without preserving line numbers) but it seems likely.
