### ISSUE TITLE
Failure to Cache New Response When Cache is Full

### ISSUE THREAD

**Issue by abbasshah17** [google/volley#145]
I have noticed that while Volley successfully caches response it does not however write over the existing old response.

Say, Volley's cache size is 5 MB and all of it is being used. Now if I make a new call to a unique link, volley does not cache the new response.

In my case I have enabled cache and am looking for 304 (`HTTP_NOT_MODIFIED`) and because the latest response is never cached I always get 200 (`HTTP_OK`) even when file/response has changed from server.

How I initialize the Queue:

    mRequestQueue = Volley.newRequestQueue(mContext);

How I add network request to the queue.

    networkRequest = new CustomNetworkResponseRequest(Request.Method.GET, url, listener, errorListener);
	if (tag != null)
		networkRequest.setTag(tag);
	networkRequest.setRetryPolicy(new DefaultRetryPolicy(2500, 1, DefaultRetryPolicy.DEFAULT_BACKOFF_MULT));
	networkRequest.setShouldCache(true);
	requestQueue.addToRequestQueue(networkRequest);

My `CustomNetworkResponseRequest`

    class CustomNetworkResponseRequestextends Request<NetworkResponse>
	{
		private final Response.Listener<NetworkResponse> mListener;
	
		CustomNetworkResponseRequestextends (int method, String url,
									 Response.Listener<NetworkResponse> listener,
									 Response.ErrorListener errorListener)
		{
		    super(method, url, errorListener);
		    mListener = listener;
		}

		@Override
		protected void deliverResponse(NetworkResponse response) 
		{
		    mListener.onResponse(response);
		}
	
		@Override
		protected Response<NetworkResponse> parseNetworkResponse(NetworkResponse response) 
		{
		    return Response.success(response, HttpHeaderParser.parseCacheHeaders(response));
		}
	}

The only way I have found it to work (just for me) is to increase the cache size. While it promises to ensure **I** always get 304 when I should (I don't have large responses or too many calls). Volley should be able to overwrite the existing cache to include the latest calls while discarding oldest.

**Comment by jpd236** [comment]
In theory this should be happening in DiskBasedCache#pruneIfNeeded which is called at the beginning of every put call.

Would you be able to attach the output of "adb logcat | grep Volley" or something similar after running "adb shell setprop log.tag.Volley VERBOSE" and executing a request that you expect should be cached (expiring old entries) but wasn't?

**Comment by uhager** [comment]
Do you use soft TTL for background refreshes? 304 responses are not cached nor delivered if the request already had a response. So if you have an entry on soft TTL, the cached response will be delivered with status OK, then the network request will be performed, but if it gets a 304, it will just finish. At least, that's how I understand the code, we don't use not-modified on our end, so I haven't tested it.

**Comment by abbasshah17** [comment]
@jpd236 I tried to get the logs but am currently unable to reproduce the issue. Unfortunately the steps to reproduce the case is really long (I still tried 3 times). Perhaps I need to disable the logs to reproduce the issue? Although I must admit I can't think of any reason why it would.

I also had checked `pruneIfNeeded` method, which led me to believe this is infact a bug.

P.S I am currently busy elsewhere but will post the logs whenever I have time in the coming week.

**Comment by jpd236** [comment]
You might try lowering the cache size to a smaller number to see if that helps reproducing it faster. Otherwise, I can't say I'm sure what's going on.

**Comment by abbasshah17** [comment]
@joebowbeer Doubt it, but will update once the issue is reproducing and can be debugged.

**Comment by jpd236** [comment]
Just checking in on this - any luck reproducing the issue?

**Comment by abbasshah17** [comment]
@jpd236 Haven't had the chance to work on it ever since. Unfortunately there's too much other high priority stuff going on right now and I just haven't found the time yet. But this is definitely on my todo list and hopefully I'll be able to work on it before April ends.

**Comment by jpd236** [comment]
I'm going to go ahead and close this out without more details on how to reproduce this. I'll be happy to reopen and look further into it if more info is provided, but as it stands, there's unfortunately not much action we can take from our side. Will also be taking a closer look at things in #57 and perhaps that will either fix the problem or expose any other latent issues.
