### ISSUE TITLE
Android Build Tools and compile SDK version

### ISSUE THREAD

**Issue by j-t-h** [google/volley#149]
When including volley as a project module in a solution, what are the current/suggested values in the gradle file for?

classpath 'com.android.tools.build:gradle:
compileSdkVersion
buildToolsVersion

The latest code has 
classpath 'com.android.tools.build:gradle:2.2.3'
compileSdkVersion 25
buildToolsVersion = '25.0.2'

I have upgraded to to latest/latest at the time, should there be any compatibility issues?

classpath 'com.android.tools.build:gradle:3.0.1'
compileSdkVersion 27
buildToolsVersion = '27.0.3'

Thanks!

**Comment by jpd236** [comment]
I'm not personally aware of any reason that newer versions shouldn't work, but in general the Volley continuous builds are done with the versions that you found in the build.gradle file, so those are the ones we ensure will work. But the intent of splitting build.gradle and rules.gradle apart is to make it possible to integrate Volley into any project and use your own versions of these tools - the library is simple enough that it should build just fine.

If you encounter any bugs or problems on newer versions, please do file them as bugs and/or send pull requests for fixes and we can take a look.
