### ISSUE TITLE
javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x79f5fc90: Failure in SSL library, usually a protocol error

### ISSUE THREAD

**Issue by hory1918** [google/volley#151]
Android4.4.3版本请求https导致以下问题，请问有什么解决方案：
javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x79f5fc90: Failure in SSL library, usually a protocol error
                                                               error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x7363ccf8:0x00000000)

**Comment by jpd236** [comment]
Sounds like an issue with the underlying HTTP library rather than Volley itself.

Might be related to the issues noted in https://github.com/google/volley/issues/77.
