### ISSUE TITLE
Is it possible to support a mechanism to query 'current' requests?

### ISSUE THREAD

**Issue by CapnSpellcheck** [google/volley#153]
Consider a case where an application has some activity that initiates a possible time-consuming request. The application should only permit one such request of this type, and the activity disables some UI elements while this operation is in progress. If the activity stops or finishes, the request should finish. However, if the activity is started again, its UI should show that there is still a request in progress, and should disable some UI until that is done.
For some concreteness, the long standing request in my case is submitting a photo to a service to be added to user's profile. If the activity is closed, the photo should still be added to the profile. But the app only allows one photo to be added at a time. 
As it is, since Volley doesn't seem to offer any information about the current requests, it is necessary to implement another singleton manager, that uses a request listener on the request queue, and basically contains all current requests and removes them once they are done. But this is duplicating part of Volley itself.
My question and suggestion here, is it possible to offer any querying mechanism at all? Due to concurrency concerns, it would have to be a copy of data; it could be a list of Request (with a stern warning that you better not mutate the object), or in simplest case, a list of tags, with a stern warning that any of the requests can be finished at any time from the moment you query.

**Comment by uhager** [comment]
If I understand you correctly, I don't think you'd need a singleton manager, just a list that you pass to the request: Use a separate RequestQueue just for this type of request with only a single NetworkDispatcher to ensure that only one request at a time is on the network (and to avoid blocking the queue that you use for other requests). Implement your own request type that has the request list as a member and hand your request list to your request when you create it. The request can then add itself to the list. Override deliverResponse and deliverError to have the request remove itself from the list.

So in your app:
RequestQueue photoUploadQueue = new RequestQueue(yourCache, yourNetwork, 1);
List requestList = new List... of whatever type

In your Request:
class SubmitPhotoRequest extends Request {
 private List requestList;
 public SubmitPhotoRequest(List requestList) {
       this.requestList = requestList;
       requestList.add(getTag());  // or this, or getUrl, or whatever
  }

public void deliverResponse(YourResponseType response) {
  super.deliverResponse(response);
  requestList.remove(getTag());
 }
... same for deliverError
}

Your app can then check that list for current requests.
Is that roughly what you're trying to do?

**Comment by jpd236** [comment]
Another option might be to extend RequestQueue and override methods to get what you need, but let me know if there are methods you'd need to add / expose in RequestQueue and we can look at that.

In general, support for this kind of work seems a bit out of scope of Volley. The behavior you describe of wanting work to continue beyond the lifetime of an Activity is really the responsibility of a Service inside your own app; regardless of whether Volley's RequestQueue keeps a request alive after you close an Activity, Android will lower your processes' priority once it's in the background, and if there are no Services running it can be killed at any time. You should consider using a Service to manage the lifecycle of this long-running task, and you can bind to and examine this service's state from the Activity/UI to determine whether a previous upload is in progress or not.

**Comment by CapnSpellcheck** [comment]
@jpd236 Thanks for pointing that out, that's an important consideration. For uhager's suggestion, I think that's a good starting point, but I don't like the idea of a Request keeping track of a list of Requests. I think combining that with a RequestFinishListener added to the Queue is more practical.
