### ISSUE TITLE
OutOfMemoryError at com.android.volley.toolbox.ByteArrayPool.getBuf(ByteArrayPool.java:101)

### ISSUE THREAD

**Issue by Son-Lam** [google/volley#155]
Hello,

I am getting error below. The payload I am getting is pretty large.

Could you help to see if there any solution for it?

Best Regards,

**I/System.out: getConfigEntry: ppatidar
W/Resources: Converting to boolean: TypedValue{t=0x3/d=0x3dc "res/anim/decelerate_interpolator.xml" a=1 r=0x10a0006}
I/System.out: getConfigEntry: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY3RvcmlkIjoyNjE1ODY2LCJleHAiOjE1MjE4NDMwMjMsImlhdCI6MTUyMTU4MzgyMywiaXNzIjoibW9zLURLUjEuRlJFIiwic2NvcGVzIjoiQWRtaW4iLCJzdWIiOiJwcGF0aWRhciJ9.MqRUlqpXsaW7EKuo5PtUORUPYsRMxkgwxMPPCFMXFE-iwRLN5Z1HuU-rzpI2GIyasuzYquRxC9gLCdXSqd3zde2WJ1dMtokFEOWg2XhU6lkSdxKmOoMZLjhcmAjhBaUtzAWgUoH9BSimtfE__lN4g20d-P3BpmdJv79FkwP3_BovDRuNN7Tq96JkQBS06lbD3xmPsxzOrhOoF-Qz5eUiwFSU_dJlsK_4kKPA5HLg3XZH5w0kT7MI_jsdfcNV7g32KqsZ8VVXlvSaC-n37iHo19uHkrTVjF5MckE_zTon8-2Z4q-ZC4cJfU374NNkm9Z0Ss8QQ4mARVeIfXsUY6jShuuxxUY-Iue73IGEMk59AdUN4kZ9RyJnTYVYdH4Y-QYvTwO3Y_mFayEs1AQFjchvXZClOQTCh5i68iVlLylWvDwFQzu7d3omHfvgAOTaiOrAXjH9xpnVnBeHe7yQaqLmnDtT7O_VC-SqZEaVZdoLk_y27cgJQMcFLuDZJz28n949tJgpXDpnt1VhgVpuoHFIp-FbNBW0NVaEO4M31o9L_YOxZWuDEg_jwGbffTmN-ov4yCJVkT_Pz1Cg6p1wAWUK26TFpdxskVZciFUDfh9hDVwMyhFauGKmuQISG-IXzZ49tiomzSskMg7iUSeQLqXT8g0UAhuKByFynSuadmti5tY
W/Resources: Converting to boolean: TypedValue{t=0x3/d=0x3dc "res/anim/decelerate_interpolator.xml" a=1 r=0x10a0006}
W/Resources: Converting to boolean: TypedValue{t=0x3/d=0x3dc "res/anim/decelerate_interpolator.xml" a=1 r=0x10a0006}
D/dalvikvm: GC_FOR_ALLOC freed 876K, 9% free 44785K/48900K, paused 25ms, total 25ms
I/dalvikvm-heap: Forcing collection of SoftReferences for 268326-byte allocation
D/dalvikvm: GC_BEFORE_OOM freed 73K, 9% free 44712K/48900K, paused 29ms, total 29ms
E/dalvikvm-heap: Out of memory on a 268326-byte allocation.
I/dalvikvm: "Thread-293" prio=5 tid=13 RUNNABLE
I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x42149488 self=0x54664310
I/dalvikvm:   | sysTid=29575 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=1415934720
I/dalvikvm:   | state=R schedstat=( 0 0 0 ) utm=103 stm=26 core=1
I/dalvikvm:     at com.android.volley.toolbox.ByteArrayPool.getBuf(ByteArrayPool.java:~101)
I/dalvikvm:     at com.android.volley.toolbox.PoolingByteArrayOutputStream.expand(PoolingByteArrayOutputStream.java:76)
I/dalvikvm:     at com.android.volley.toolbox.PoolingByteArrayOutputStream.write(PoolingByteArrayOutputStream.java:84)
I/dalvikvm:     at com.android.volley.toolbox.BasicNetwork.inputStreamToBytes(BasicNetwork.java:280)
I/dalvikvm:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:152)
I/dalvikvm:     at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:120)
I/dalvikvm:     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:87)
W/dalvikvm: threadid=13: thread exiting with uncaught exception (group=0x41e2ad58)
E/AndroidRuntime: FATAL EXCEPTION: Thread-293
                  Process: com.tesla.mobilemos, PID: 29516
                  java.lang.OutOfMemoryError
                      at com.android.volley.toolbox.ByteArrayPool.getBuf(ByteArrayPool.java:101)
                      at com.android.volley.toolbox.PoolingByteArrayOutputStream.expand(PoolingByteArrayOutputStream.java:76)
                      at com.android.volley.toolbox.PoolingByteArrayOutputStream.write(PoolingByteArrayOutputStream.java:84)
                      at com.android.volley.toolbox.BasicNetwork.inputStreamToBytes(BasicNetwork.java:280)
                      at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:152)
                      at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:120)
                      at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:87)
E/HAL: hw_get_module_by_class path = /system/lib/hw/gralloc.msm8960.so
I/ActivityManagerProxy: Timeline: Activity_idle id: android.os.BinderProxy@420fc550 time:20075294
Disconnected from the target VM, address: 'localhost:8650', transport: 'socket'**

**Comment by jpd236** [comment]
As noted at: https://developer.android.com/training/volley/index.html

"Volley is not suitable for large download or streaming operations, since Volley holds all responses in memory during parsing. For large download operations, consider using an alternative like DownloadManager."

The failing operation is trying to allocate a byte array large enough to store the whole response, which is precisely the problem noted here. This is out of the scope of what Volley can accomplish, and generally not advisable given the memory impact and lack of a way to resume a partial download.
