### ISSUE TITLE
ParseError Wrong Reading Response

### ISSUE THREAD

**Issue by caktoy** [google/volley#156]
I get ParseError when Json returns.

This is the error message:
![dkp_error1](https://user-images.githubusercontent.com/6917446/37874859-46c8fb88-3061-11e8-89fc-c24b0949959b.png)

And this is the response I get using Postman
![dkp_postman](https://user-images.githubusercontent.com/6917446/37874890-a24a7f5e-3061-11e8-859b-a1cc55900964.png)

So where is the source '<div' on my error message?

**Comment by uhager** [comment]
I have never used Postman, but a quick search showed that it ignores HTML in pretty view: https://github.com/postmanlabs/postman-app-support/issues/3635 
So it seems that the server is returning HTML, and Volley is complaining (as it should) while Postman is hiding it.

**Comment by caktoy** [comment]
Oke @uhager, I get it, thank you very much for the solution. #closed
