### ISSUE TITLE
Current Stable Snapshot build and 1.1.1 release.

### ISSUE THREAD

**Issue by j-t-h** [google/volley#158]
Is com.android.volley:volley:1.1.1-20171227.180452-3 the latest stable snapshot?

I need to pick a version to for releasing our app and 1.1.0 does not seem the right choice.

Is there still a wait on the official 1.1.1 release?

**Comment by jpd236** [comment]
The latest snapshot in general can be found by looking for the newest timestamp in:

https://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/volley/volley/

so no, that's not the newest one, which is volley-1.1.1-20180118.172331-6.

In terms of stability, while you may run into more issues than you would by pointing to an official version, in general we don't check in any changes which are expected to be unstable, and this build has been fixed for months at this point, so I personally would be reasonably confident in the stability of this snapshot release.

We have not released 1.1.1 officially yet as there are still [open](https://github.com/google/volley/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.1.1) bugs to investigate that we need to get to.  I hope we can do it soon but we can't offer a specific date at this time.
