### ISSUE TITLE
java.lang.IllegalMonitorStateException on CacheDispatcher process request

### ISSUE THREAD

**Issue by kenfourdesire** [google/volley#159]
We got the following crash log only on android 7, is there any idea?
(volley version 1.1.0)
```
Caused by java.lang.IllegalMonitorStateException
       at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:126)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1260)
       at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:434)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:521)
       at com.android.volley.CacheDispatcher.processRequest(CacheDispatcher.java:113)
       at com.android.volley.CacheDispatcher.run(CacheDispatcher.java:96)
```

**Comment by jpd236** [comment]
I haven't seen it before and can't say it makes much sense. It sounds likely to be a device specific issue or older platform bug. CacheDispatcher is just using a private PriorityBlockingQueue on a single thread and taking entries from it in a loop; there's zero reason I can see that calling take() on that queue should ever do something like this.

Doesn't seem like something we can do much about in Volley, but if you can provide a way for us to reproduce the issue, or suggest a workaround that fixes the issue on the affected devices, then we can take a closer look.

It would be helpful to have the message from the stack trace as well.

**Comment by kenfourdesire** [comment]
[com.fourdesire.fortunecity_issue_2542_crash_5ADD9C1000FB00013499F4E3895A1EA0_DNE_0_v2.txt](https://github.com/google/volley/files/1937692/com.fourdesire.fortunecity_issue_2542_crash_5ADD9C1000FB00013499F4E3895A1EA0_DNE_0_v2.txt)

Hi, @jpd236 
I found there are two threads using the CacheDispatcher. You can find it in the stack trace file.
Maybe I use volley in the wrong way?

**Comment by jpd236** [comment]
I only see one thread referencing CacheDispatcher (#43. Thread-429). In any case, CacheDispatcher is itself a thread so there shouldn't be more than one thread using a single instance of one. Like I said - it's highly suspicious if this is only happening on one device / older platform version.
