### ISSUE TITLE
Requet Progressbar

### ISSUE THREAD

**Issue by hernanyoliveira** [google/volley#164]
It would be possible to add a progress bar on  jsonObjectRequest ??
That would be optionial. If i want probressbar = view.visivel otherwise view.invisible. !!
Thanks a lot.

**Comment by jpd236** [comment]
Progress for individual requests is out of Volley's scope:

https://github.com/google/volley/wiki/Frequently-Asked-Questions#why-doesnt-volley-support-large-downloadsuploads
