### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by nitishmaropost** [google/volley#167]
Got this exception at runtime on integration Volley 1.1.0  
  

> E/UncaughtException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/volley/toolbox/Volley;   
  
This is how I added dependency :  
  

> dependencies {
>     implementation fileTree(include: ['*.jar'], dir: 'libs')
>     testImplementation 'junit:junit:4.12'
>     implementation 'com.android.support:appcompat-v7:27.1.1'
>     implementation 'com.google.android.gms:play-services-base:12.0.1'
>     implementation 'com.google.android.gms:play-services-location:12.0.1'
>     implementation "com.google.firebase:firebase-messaging:15.0.0"
>     implementation 'com.google.firebase:firebase-core:12.0.1'
>     implementation 'com.android.volley:volley:1.1.0'
> 
>     apply plugin: 'maven'
> }

**Comment by jpd236** [comment]
The class is clearly part of the build, and worked at compile time, so it sounds like something is wrong with your build infrastructure. If you can provide a fully working example project, we could take a closer look, but I might suggest you dig into this more from the Gradle side than the Volley side as this seems unlikely to be a bug in Volley itself.

**Comment by nitishmaropost** [comment]
I am adding Volley in a custom framework I am working on, not an application project itself. As far as grade is concerned, there is nothing wrong with it since other dependencies work just fine.
Also, I request you not to close the issue by yourself unless it is resolved completely. So kindly reopen it.

**Comment by jpd236** [comment]
Sorry that you're running into issues, but I don't see any action we can take here from your report. A simple test application with this dependency works fine, and there are no other reports of an issue like this. We close out bugs if they are not actionable, but I can certainly reopen it if you can provide enough details (ideally a small test app that we can build/run locally) such that we can reproduce the issue on our side.

Maybe Proguard is stripping the library out or something, but I can't possibly determine that from just what's been reported.

**Comment by innovian** [comment]
+1
