### ISSUE TITLE
RequestQueue.java uses unchecked or unsafe operations

### ISSUE THREAD

**Issue by j-t-h** [google/volley#168]
In the latest Android Studio/Gradle I am getting this Java compiler issue/warning in the RequestQueue.java.

uses unchecked or unsafe operations. 

Looks like it might be narrowed down to unchecked assignment in:

synchronized (mFinishedListeners) {
          for (RequestFinishedListener<T> listener : mFinishedListeners) {
            listener.onRequestFinished(request);
          }
        }

**Comment by jpd236** [comment]
I think this is what was discussed in https://github.com/google/volley/pull/109. We can add a @SuppressWarnings but that's probably it without a breaking API change,

**Comment by abrahamsamuelsmithpaul** [comment]
C:\Users\SAM\Downloads\OnlineShopping2\app\src\main\java\com\example\onlineshopping\SettinsActivity.java:
uses unchecked or unsafe operations.
Recompile with -Xlint:unchecked for details.
