### ISSUE TITLE
About Gson used in Volley

### ISSUE THREAD

**Issue by jarvisyin** [google/volley#173]
I see JsonObjectRequest in toolbox
maybe Gson is more useful and efficient.

Why not try to create GsonObjectRequest<Object> ?

It's there any other consider?

Independence from each other between Volley and Gson?

**Comment by jpd236** [comment]
Volley's core library is intentionally dependency-free to avoid tying users to one particular solution / pulling in unnecessary dependencies. It certainly makes sense to create a GsonRequest or similar and use that, but it wouldn't fit into the core library itself.

For example, the Volley docs actually provide a GsonRequest:

https://developer.android.com/training/volley/request-custom#example-gsonrequest

**Comment by jarvisyin** [comment]
What about JsonObjectRequest
It seems a particular solution that GsonRequest can do. and do batter
