### ISSUE TITLE
Enable Cache by default only for GET requests

### ISSUE THREAD

**Issue by lucasiturbide** [google/volley#184]
My recommendation is to set the default value for `mShouldCache` to true only when the constructor passes a `GET` as method

Here is why:

I recently encountered a bug when upgrading to Volley 1.1.0, and maybe because before was not working, or it is an optimization for the caching system.
I have several POST requests (for a SOAP API) and they have all the same URL, so the cache key will be the same for all of them, but the response object is different.
The problem raises only when two parallel requests are done, and the request queue separates one of them and make it wait for the response of the first request, then delivers that same response to both requests. This can cause a ClassCastException.
Since the POST data is different, I expect different responses, and most POST requests (or PUT or any other that is not GET) will expect different responses (or confirmation that the POST data has been successfully processed).

**Comment by phearme** [comment]
@lucasiturbide possible duplicate of https://github.com/google/volley/issues/154 planned for 1.2.0
