### ISSUE TITLE
Solved: Volley returns null error after hitting an endpoint that sends email

### ISSUE THREAD

**Issue by esdeguzman** [google/volley#186]
Good day!

I have this Android app that does this app logic,

User -> Reserves an item using Android app
Android app -> Hits server API to save the item
Server -> Saves the item and send an email to the User then returns a JSON response that contains reservation details

It works perfectly fine on Postman, but when I use Volley, the server does saves the reservation but then Volley receives an onErrorResponse of null. Below is the code I am using,

```
StringRequest stringRequest = new StringRequest(Request.Method.POST, url,
             new Response.Listener<String>() {
                 @Override
                 public void onResponse(String response) {
                     try {
                         JSONObject reservationJson = new JSONObject(response);
                         ...
                     } catch (JSONException e) {
                         e.printStackTrace();
                     }
                 }
             }, new Response.ErrorListener() {
         @Override
         public void onErrorResponse(VolleyError error) {
             Log.d(TAG, "onErrorResponse: " + error.getMessage());
         }
     });
    
     // Add the request to the RequestQueue.
     queue.add(stringRequest);
 }
```

---

As I was debugging, I noticed that two reservations are saved upon reserving an item, I researched and found out that it has been a problem of Volley for some of its POST requests aka double request. I added these lines of code:

> DefaultRetryPolicy  retryPolicy = new DefaultRetryPolicy(0, -1, DefaultRetryPolicy.DEFAULT_BACKOFF_MULT);
        stringRequest.setRetryPolicy(retryPolicy);

Which resolves my problem.

**Comment by jpd236** [comment]
This isn't specific to Volley, but - be warned that mobile networks are inherently flaky; you may be testing on a good and stable connection, but think about what happens if your user is using the device on a less reliable network. It's very possible for a request to reach the server but the reply not to get back to the device. In this case, by trying only once, you'll not only surface an error to the user on the first try, but they'll also get an email indicating success, and the request would fail on subsequent tries.

Typically, the safer way to handle this is to make the server implementation idempotent - in other words, able to handle the same request from the device multiple times without changing the response. For this particular case, I could imagine implementing the "save item" operation on the server to return the existing reservation details if one already exists (because a previous request went through) rather than returning an error; then no special handling is required by the client, which can retry as many times as needed. Or you could have a particular error code like ITEM_ALREADY_EXISTS and build client logic to handle that case as appropriate.

**Comment by esdeguzman** [comment]
@jpd236 I was building a working android app prototype here, and I am very grateful for your suggestion. Will probably implement it on the project! I am still a noob on testing side so this is really appreciated. Thank you!

**Comment by hadighasemian** [comment]
answer is here:
https://stackoverflow.com/a/52242436/2919718

**Comment by alosada1960** [comment]
Soy un estudiante autodidacta de la programación en Android con algunos conocimientos básicos de programación en Java, PHP y SQL. En mis ejercicios prácticos cree esta pequeña aplicación para probar los conocimientos que voy adquiriendo y se me ha presentado el siguiente problema:

Esta aplicación funcionaba y funciona con las versiones de Android anteriores a SDK 26 pero una vez que cambio a las últimas versiones 26, 27 y 28 la respuesta de Volley es null, estoy utilizando Wamp como servidor local y la consulta a la DB o ejecución del "programa.php" en el navegador funciona perfectamente.
Realmente entiendo que no tengo todos los conocimientos para lograr darme cuenta de qué falta o donde esta el error. Por favor necesito de alguna persona que desinteresadamente ayude a este mortal que lo que mas desea es aprender. Gracias

A continuación les muestro el código:



public class MainActivity extends AppCompatActivity implements View.OnClickListener {

    TextView textView;
    EditText editText,editText2;
    Button button;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        textView = findViewById(R.id.textView);

        editText = findViewById(R.id.editText);
        editText2 = findViewById(R.id.editText2);
        button = findViewById(R.id.button);
        button.setOnClickListener(this);

    }

    @Override
    public void onClick(View v) {

        String usu = editText.getText().toString();
        String pass = editText2.getText().toString();
        if (usu.length() == 0)
            Toast.makeText(getApplicationContext(), "El campo Nombre no puede estar en blanco", Toast.LENGTH_LONG).show();


        if (v.getId() == R.id.button){

            final String url = "http: ...";

           JsonArrayRequest req = new JsonArrayRequest(url, new Response.Listener<JSONArray>() {
                @Override
                public void onResponse(JSONArray response) {

                    if (response.length() == 0) {
                        Toast.makeText(getApplicationContext(), "El usuario no existe en el Sistema", Toast.LENGTH_LONG).show();
                    }else {
                        try {

                            for (int i = 0; i < response.length(); i++) {

                                JSONObject id = (JSONObject) response.get(i);
                                JSONObject dato = id.getJSONObject("id");
                                System.out.println("dato mainactivity = " + dato);

                                int condicion = dato.getInt("2");

                                switch (condicion) {
                                    case 1: {
                                        Intent intent1 = new Intent(getApplicationContext(), Administrar.class);
                                        startActivity(intent1);
                                        break;
                                    }
                                    case 0: {
                                        Intent intent2 = new Intent(getApplicationContext(), Ventas.class);
                                        startActivity(intent2);
                                        break;
                                    }
                                    default:
                                        break;
                                }
                            }

                        } catch (JSONException e) {
                            e.printStackTrace();
                            Toast.makeText(getApplicationContext(), "ERROR : " + e.getMessage(), Toast.LENGTH_LONG).show();
                        }

                    }
                }
            }, new Response.ErrorListener() {
                @Override
                public void onErrorResponse(VolleyError error) {
                    NetworkResponse statusCode = error.networkResponse;
                    System.out.println("Codigo " + statusCode);

                }
            });
            RequestQueue cola = Volley.newRequestQueue(getApplicationContext());
            cola.add(req);

        }

    }
}

**Comment by ankitagreeya** [comment]
Anyone have idea this issue

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.volley.Response.isSuccess()' on a null object reference
2023-07-28 15:05:52.328	ERROR:	AndroidRuntime : at com.android.volley.ExecutorDelivery$b.run(SourceFile:3)
2023-07-28 15:05:52.328	ERROR:	AndroidRuntime : at android.os.Handler.handleCallback(Handler.java:938)
