### ISSUE TITLE
Android Studio Warning: 1.1.0 deprecated

### ISSUE THREAD

**Issue by cquinn96** [google/volley#187]
Android Studio 3.1 and 3.2 are suggesting that Volley 1.1.0 is deprecated with a recommendation to switch to 1.1.0 (the same version). See https://imgur.com/vEPt9rE

**Comment by jpd236** [comment]
This issue has been reported to the Android Studio team here: https://issuetracker.google.com/79219523

Unfortunately, it doesn't appear to be in Volley's direct control.
