### ISSUE TITLE
How to manage response different from request

### ISSUE THREAD

**Issue by Trusted97** [google/volley#192]
Hi 
I'm using volley for retrieve data from an Api that return a JsonArray if post parameters is correct or a string if there are an error. I'm using JsonArrayRequest and obviously it give me this error 

`com.android.volley.ParseError: org.json.JSONException: Value error of type java.lang.String cannot be converted to JSONArray`

Could i retrieve the error string or i need to make a CustomRequest?

**Comment by jpd236** [comment]
If it's trying to parse your response as JSON, it means the server returned an HTTP 200, which seems semantically incorrect if there's an error. If you control the server, I'd suggest returning an appropriate error code. Then Volley won't attempt to parse the response as JSON in the error scenario, and instead your ErrorListener can inspect the NetworkResponse for the string message.

If you don't control the server, then you'll need to make your own Request and override parseNetworkResponse to handle this case.
