### ISSUE TITLE
FatalException

### ISSUE THREAD

**Issue by gccgithub** [google/volley#197]
05-31 08:44:40.156 20098 20124 E AndroidRuntime: Process: com.vivo.magazine, PID: 20098

05-31 08:44:40.156 20098 20124 E AndroidRuntime: java.lang.IllegalThreadStateException

05-31 08:44:40.156 20098 20124 E AndroidRuntime: 	at java.lang.Thread.start(Thread.java:724)

05-31 08:44:40.156 20098 20124 E AndroidRuntime: 	at com.android.volley.c.start(RequestQueue.java:145)

**Comment by jpd236** [comment]
Unfortunately there's not enough information here for us to be able to diagnose the problem. My best guess is that you're calling start() on the same RequestQueue instance from multiple threads, which isn't safe and shouldn't be necessary.

If that's not the case, please provide more information - ideally a small sample app that reproduces the issue, and at a bare minimum the version of Volley you are using and more details about the code that's crashing.
