### ISSUE TITLE
OutOfMemoryError on com.android.volley.toolbox.ByteArrayPool.getBuf

### ISSUE THREAD

**Issue by hadasmeitav** [google/volley#199]
We're having this crash : 
`Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 227840 byte allocation with 185992 free bytes and 181KB until OOM, max allowed footprint 268435456, growth limit 268435456       at com.android.volley.toolbox.ByteArrayPool.getBuf(ByteArrayPool.java:101)       at com.android.volley.toolbox.PoolingByteArrayOutputStream.expand(PoolingByteArrayOutputStream.java:76)       at com.android.volley.toolbox.PoolingByteArrayOutputStream.write(PoolingByteArrayOutputStream.java:84)       at com.android.volley.toolbox.BasicNetwork.inputStreamToBytes(BasicNetwork.java:280)       at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:152)       at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:120)       at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:87)`

We know that volley loads memory in cache, and this is basically a load of more memory that volley can handle, and we should use another library for loading a lot of memory in cache.
But frankly, this only happens in low memory old devices, and very rarely. Its not an issue of loading to much in the memory, our data parsed by volley isn't big (few bytes).
 
We've integrated volley library, and we can't dedicate more days to integrate another library. 
This error obviously was discovered in production environment. 

As far as we're concern, this is a very simple try catch on your end, so we failed to realized why [this ticket](https://github.com/google/volley/issues/155) wasn't fixed before.

**Comment by hadasmeitav** [comment]
hi @joebowbeer , thanks for the response. 
We have been using 1.1.0 version for a while, and moved to 1.1.0-rc2 recently. 

I agree with you that its bad practice, but think about it from our point of view : We built an sdk, and use volley within. Our SDK is in use by a company, and when the volley generates `OutOfMemoryError` the app of the company crashes. 
We have no way of handing this error, and it looks bad to the user (who has no awareness of the backstage of the crash) to see that the application crashes. 

I have to stress out, that this error occurs on low memory devices (and quite old, but still - exists in the market), and its not an issue of violation of the volley library. We're using the library as we should, and according to the guidlines .. an error like so is quite dangerous.

**Comment by joebowbeer** [comment]
@hadasmeitav The latest version is [1.1.1-SNAPSHOT](https://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/volley/volley/1.1.1-SNAPSHOT/)

See [Issue 11 comment](https://github.com/google/volley/issues/11#issuecomment-314296577) for instructions.

If your app needs to do something special with unhandled exceptions, I suggest setting a default UncaughtExceptionHandler:

https://developer.android.com/reference/java/lang/Thread.UncaughtExceptionHandler

**Comment by hadasmeitav** [comment]
Hi @joebowbeer 
This version is a snapshot version, and not even listed in the [released versions](https://github.com/google/volley/releases).
If you know that the crash we have fixes the problem above, i'd use it, however, i couldn't find that the crash was fixed in this version. 
Seems 'dangerous' to use a version which is labeled 'snapshot' in our production environment. 

We have an UncaughtExceptionHandler in our system, it doesn't catch all of the crashes, and not the one above. You can see lots of post regarding this.

**Comment by jpd236** [comment]
I really don't see anything Volley can do about this. It's OOMing trying to allocate 227 KB, which is not a "few bytes" as was described, but not very large either. If I'm reading the error message right, the app has a max heap size of ~268MB, which is substantially larger.

I would be inclined to suspect a memory leak somewhere else in your app (or perhaps in Volley? but we would need evidence of that). The fact that it just happens on lower RAM devices would be consistent with that, as such devices have a lower ceiling before crashes will start happening. I would recommend investigating further in that direction.

FWIW, BasicNetwork provides a constructor for which you can provide your own ByteArrayPool implementation. If you really suspect that Volley is the problem here, then you can try providing your own implementation.
