### ISSUE TITLE
NoClassDefFoundError when targetSdk=28

### ISSUE THREAD

**Issue by seventhmoon** [google/volley#200]
Recent behavior change in P will affect this library.

> An app can be affected if it uses a non-standard ClassLoader that explicitly delegates to the system ClassLoader. These apps need to delegate to the app ClassLoader instead when looking for classes in org.apache.http.*. If they delegate to the system ClassLoader, the apps will fail on Android P with a NoClassDefFoundError, because those classes are no longer known to the system ClassLoader. To prevent similar problems in the future, apps should in general load classes through the app ClassLoader rather than accessing the system ClassLoader directly.

https://developer.android.com/preview/behavior-changes#apache-nonp

Application with this lib and targets P will be affected.

> E/AndroidRuntime:` FATAL EXCEPTION: Thread-6
>     Process: com.androidfung.geoip, PID: 26781
>     java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
>         at el.b(:com.google.android.gms.dynamite_mapsdynamite@12848063@12.8.48 (100408-196123505):3)
>         at ek.a(:com.google.android.gms.dynamite_mapsdynamite@12848063@12.8.48 (100408-196123505):4)
>         at em.a(:com.google.android.gms.dynamite_mapsdynamite@12848063@12.8.48 (100408-196123505):51)
>         at com.google.maps.api.android.lib6.drd.ap.a(:com.google.android.gms.dynamite_mapsdynamite@12848063@12.8.48 (100408-196123505):11)
>         at dw.a(:com.google.android.gms.dynamite_mapsdynamite@12848063@12.8.48 (100408-196123505):16)
>         at dw.run(:com.google.android.gms.dynamite_mapsdynamite@12848063@12.8.48 (100408-196123505):61)
>      Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/system/priv-app/PrebuiltGmsCorePi/app_chimera/m/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000006/MapsDynamite.apk!/lib/arm64-v8a, /system/lib64]]
>         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:126)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
>         at ad.loadClass(:com.google.android.gms.dynamite_dynamiteloader@12848063@12.8.48 (100408-196123505):25)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by edenman** [comment]
@seventhmoon did you find a workaround for this?  I'm running into the same issue but I don't use Volley in my app.

**Comment by edenman** [comment]
nevermind, found workaround on https://issuetracker.google.com/issues/79478779

**Comment by lawloretienne** [comment]
Yep the workaround the the google issue worked
<uses-library android:name="org.apache.http.legacy" android:required="false"/>

**Comment by vikas0** [comment]
> <uses-library android:name="org.apache.http.legacy" android:required="false"/>

how to put this in the code?

**Comment by barotia** [comment]
@vikas0 In manifest, in application tag.

**Comment by altairmizuchi** [comment]
Hello everyone! This has not helped in my case. Is there any special place inside an <application> tag where I should place uses-library?

**Comment by mumu007** [comment]
> Hello everyone! This has not helped in my case. Is there any special place inside an tag where I should place uses-library?

application tag in AndroidManifest.xml

**Comment by Amin-Said** [comment]
@lawloretienne  
I face the same problem and uses` <uses-library android:name="org.apache.http.legacy" android:required="false"/>` in my manifest but that's not solve it any other solution? 
**here is a full details of the error** https://stackoverflow.com/questions/55514956/data-not-loading-from-server-using-volley-after-upgrade-my-compilesdkversion-to

**Comment by markosole** [comment]
Problem still has not been resolved and workaround works. I am using NativeScript and targeting latest API 28. Just in case if someone need more details. 

    <application  android:hardwareAccelerated="true" android:usesCleartextTraffic="true">
        <uses-library android:name="org.apache.http.legacy" android:required="false"/>
			.
				.
				.
				.
				.
			.
    </application>

**Comment by jpd236** [comment]
Sorry for not commenting here (the issue was self-closed by the reporter so I never took a closer look at it).

From Volley's perspective, you should not need the <uses-library> declaration as long as you are not using the ApacheHttpStack (which is deprecated). If you are just using Volley.newRequestQueue without providing an HttpStack, or if you are using HurlStack or another stack which extends BaseHttpStack, the library should not attempt to use Apache HTTP at runtime, and you should not need to request the library in your AndroidManifest.xml.

As far as I can tell the stack trace in the first comment has nothing at all to do with Volley. It's a crash in the Google Maps SDK.

If you are having a problem with _Volley_, and you are not using the Apache library or don't believe you should be, then please let us know.

If you are having a problem with another SDK or library, then please investigate with that SDK/library's contacts.
