### ISSUE TITLE
ImageListener.onResponse is not been called in some cases

### ISSUE THREAD

**Issue by forceLain** [google/volley#209]
Steps to repro:
1. Initialize a basic Volley request queue`Volley.newRequestQueue(this)`
2. Initialize ImageLoader with no cache `imageLoader = ImageLoader(queue, NoImageCache())`
```
class NoImageCache : ImageLoader.ImageCache {
    override fun getBitmap(url: String?): Bitmap? = null
    override fun putBitmap(url: String?, bitmap: Bitmap?) {}
}
```
3. Create list of items using RecyclerView and NetworkImageView as its items. For each image view, use the same URL.
4. Scroll the list fast

Result:
Some image views are not loading

Sample project: https://github.com/forceLain/VolleyResponseBug

**Comment by forceLain** [comment]
![volley-list-2](https://user-images.githubusercontent.com/3397249/43139580-52f776e4-8f7c-11e8-908e-8b7c33360587.gif)

**Comment by forceLain** [comment]
You can find a sample project here: https://github.com/forceLain/VolleyResponseBug
I feel that creating an array for each result might be not that efficient. Feel free to give any suggestions, I'll be happy to update the fix.

**Comment by jpd236** [comment]
Thanks for the explanation and sample project!

I think there's a simpler and more efficient fix here; there's no reason to even start the second request if the first one is done and just pending batch delivery. We can just add the second request to the first request's batch delivery list. Please take a look at #212 - I verified it resolves the issue in your sample project but would be interested in knowing if I've misunderstood the problem or if there's a problem with that approach.

**Comment by forceLain** [comment]
Sorry for the delay, your changes fix the issue, thanks!
