### ISSUE TITLE
Support for multiple identical headers

### ISSUE THREAD

**Issue by jpd236** [google/volley#21]
Previous discussion: https://groups.google.com/forum/#!topic/volley-users/rNTlV-LORzY

The main use case here seems to be server responses with multiple Set-Cookie headers. It looks like a valid feature request, but the concern is that this would require breaking the public API.

**Comment by mousumikhatua** [comment]
I am facing the similar issues.
I get multiple cookie sets with Set-Cookie headers.
In HurlStack.java line 122 - it's only considering the first one.
Need an API update so that I can get all the cookie values.

**Comment by gonzadocarmo** [comment]
So, I'm seeing 2 ways here:
- breaking the public API --> then v2.0.0.
- not breaking the public API --> extending/adapting it so that it does not break the current API. Something equals or similar to @georgiecasey solution (https://github.com/georgiecasey/android-volley-duplicateheadersfix)

**Comment by jpd236** [comment]
I looked a little more at this while [working on cleaning up Volley's Apache HTTP dependency](https://github.com/google/volley/issues/2#issuecomment-296517605), and I think it can be done without breaking the current API.

The new BaseHttpStack interface introduced by the above fix obtains a Map<String, List<String>> of response headers instead of a Map<String, String> from the HTTP stack, which is the first step. From there, we can safely add a new Map<String, List<String> field to NetworkResponse and deprecate the old one while still populating it for backwards compatibility with the first header for a particular key. We'd need to make a similar change to Cache.Entry and read in the duplicate keys in DiskBasedCache (which we can thankfully do without changing the on-disk format, since they're just stored as a flat list; the duplicate entries are dropped on read).

So all told, I think we should be able to fix this without breaking public API, which is good. If someone would like to send a PR for this, I'd recommend waiting until #2 is resolved and then following the above path. Otherwise I will try to get to this at some point soon.

**Comment by shamolideguzhou** [comment]
.

**Comment by jpd236** [comment]
https://github.com/google/volley/pull/91 out for review to implement the approach described above.

**Comment by jpd236** [comment]
This should now be resolved in master and will make it to a 1.0.1-SNAPSHOT build soon.

NetworkResponse (and Cache.Entry) now includes an "allHeaders" field which is the raw list of all headers returned by the server and thus can include duplicates by name. You may iterate over this list if non-null to find all headers with a given name. This is not case-sensitive, FYI; I opted not to pre-process the list as a case-insensitive `Map<String, List<String>>` because that'd be a fairly expensive structure to create in the common case that clients don't actually care about reading multiple headers with the same key. So for example, if you want all "Set-Cookie" headers, I'd iterate through the full list for any Headers for which `"Set-Cookie".equalsIgnoreCase(header.getName())`.

If you are using a built-in HTTP stack (HurlStack/HttpClientStack), these fields should be populated and can be used directly.

If you are using another stack implementation, you will need to update the implementation atop the new BaseHttpStack for the new fields to be populated. There are some instructions on how to do this here: https://github.com/google/volley/wiki/Migrating-from-Apache-HTTP

Custom Network and Cache implementations would also need to be updated to populate the new fields. BasicNetwork and DiskBasedCache are fine.
