### ISSUE TITLE
Volley uses the refresh token policy

### ISSUE THREAD

**Issue by wxz-Android** [google/volley#213]
There is such a need to use refresh_token to refresh the token so that the user is always online,I have not found a good solution.
I hope that some experts will give some suggestions, thank you very much.
The strategy I am using now is to add a refreshToken to the failed retry.
This is a custom failure retry.

`

    public class CustomRetryPolicy implements RetryPolicy {
    private static final String TAG = "Refresh";
    private Request request;
    /**
     * The current timeout in milliseconds.
     */
    private int mCurrentTimeoutMs;

    /**
     * The current retry count.
     */
    private int mCurrentRetryCount;

    /**
     * The maximum number of attempts.
     */
    private final int mMaxNumRetries;

    /**
     * The backoff multiplier for the policy.
     */
    private final float mBackoffMultiplier;

    /**
     * The default socket timeout in milliseconds
     */
    public static final int DEFAULT_TIMEOUT_MS = 2500;

    /**
     * The default number of retries
     */
    public static final int DEFAULT_MAX_RETRIES = 1;

    /**
     * The default backoff multiplier
     */
    public static final float DEFAULT_BACKOFF_MULT = 1f;

    /**
     * Constructs a new retry policy using the default timeouts.
     */
    public CustomRetryPolicy() {
        this(DEFAULT_TIMEOUT_MS, DEFAULT_MAX_RETRIES, DEFAULT_BACKOFF_MULT);
    }

    /**
     * Constructs a new retry policy.
     *
     * @param initialTimeoutMs  The initial timeout for the policy.
     * @param maxNumRetries     The maximum number of retries.
     * @param backoffMultiplier Backoff multiplier for the policy.
     */
    public CustomRetryPolicy(int initialTimeoutMs, int maxNumRetries, float backoffMultiplier) {
        mCurrentTimeoutMs = initialTimeoutMs;
        mMaxNumRetries = maxNumRetries;
        mBackoffMultiplier = backoffMultiplier;
    }

    /**
     * Returns the current timeout.
     */
    @Override
    public int getCurrentTimeout() {
        return mCurrentTimeoutMs;
    }

    /**
     * Returns the current retry count.
     */
    @Override
    public int getCurrentRetryCount() {
        return mCurrentRetryCount;
    }

    /**
     * Returns the backoff multiplier for the policy.
     */
    public float getBackoffMultiplier() {
        return mBackoffMultiplier;
    }

    /**
     * Prepares for the next retry by applying a backoff to the timeout.
     *
     * @param error The error code of the last attempt.
     */
    @SuppressWarnings("unchecked")
    @Override
    public void retry(VolleyError error) throws VolleyError {
        mCurrentRetryCount++;
        mCurrentTimeoutMs += (mCurrentTimeoutMs * mBackoffMultiplier);
        if (!hasAttemptRemaining()) {
            throw error;
        }
        //401 and 403 
        if (error instanceof AuthFailureError) {//Just token invalid,refresh token
            AuthFailureError er = (AuthFailureError) error;
            if (er.networkResponse != null && er.networkResponse.statusCode == HttpURLConnection.HTTP_UNAUTHORIZED) {
                //Count is used to reset the flag
                RefreshTokenManager instance = RefreshTokenManager.getInstance();
                instance.increaseCount();
                CUtils.logD(TAG, "come retry count: " + instance.getCount());
                boolean ok = instance.refreshToken();
                if (ok) {
                    Map<String, String> headers = request.getHeaders();
                    String[] tokens = instance.getTokens();
                    headers.put("token", tokens[0]);
                    Log.d(TAG, "retry:success");
                } else {
                    throw error;
                }
            }
        }

    }

    /**
     * Returns true if this policy has attempts remaining, false otherwise.
     */
    protected boolean hasAttemptRemaining() {
        return mCurrentRetryCount <= mMaxNumRetries;
    }

    public Request getRequest() {
        return request;
    }

    public void setRequest(Request request) {
        this.request = request;
    }
}

`
RefreshToken

`

    public class RefreshTokenManager {
    private static final String TAG = "Refresh";
    private static RefreshTokenManager instance;
    private final RefreshFlag flag;
    /**
     *retry count
     */
    private AtomicInteger count = new AtomicInteger();

    public int getCount() {
        return count.get();
    }

    public  int increaseCount() {
        return count.getAndIncrement();
    }

    public void resetCount() {
        this.count.set(0);
    }

    /**
     * 锁
     */
    private Lock lock;

    public static RefreshTokenManager getInstance() {
        synchronized (RefreshTokenManager.class) {
            if (instance == null) {
                synchronized (RefreshTokenManager.class) {
                    instance = new RefreshTokenManager();
                }
            }
        }
        return instance;
    }

    private RefreshTokenManager() {
        flag = new RefreshFlag();
        lock = new ReentrantLock();
    }

    public void resetFlag() {
        lock.lock();
        RefreshFlag flag = getFlag();
        flag.resetFlag();
        lock.unlock();
    }

    protected boolean refreshToken() {
       lock.lock();
        RefreshFlag flag = getFlag();
        //Reset the flag so that the next time the token fails, it can enter normally.
        if (flag.isFailure()) {
            if (count.decrementAndGet() == 0) {
                resetFlag();
            }
            lock.unlock();
            return false;
        } else if (flag.isSuccess()) {
            CUtils.logD(TAG, "decrease retry count: " + instance.getCount());
            if (count.decrementAndGet() == 0) {
                count.incrementAndGet();
                flag.resetFlag();
            } else {
                lock.unlock();
                return true;
            }
        }
        // refreshToken is doing.
        flag.setDoing();
        //Upload refresh_token and get the response from the server
        String response = postRefreshTokenRequest();
        CUtils.logD(TAG, "refreshToken: response " + response);
        if (!TextUtils.isEmpty(response)) {
            try {
                JSONObject jsonObject = new JSONObject(response);
                JSONObject data = jsonObject.optJSONObject("data");
                if (data != null) {
                    String token = data.optString("token");
                    String refreshToken = data.optString("refresh_token");
                    CUtils.logD(TAG, "refreshToken: token : " + token + "\n" + "refresh_token : " + refreshToken);
                    if (!TextUtils.isEmpty(token) && !TextUtils.isEmpty(refreshToken)) {
                        //success,save token and refresh_token
                        saveTokens(token, refreshToken);
                        CUtils.logD(TAG, "run: success  notify ");
                        flag.setSuccess();
                        if (count.decrementAndGet() == 0) {
                            resetFlag();
                        }
                        CUtils.logD(TAG, "decrease retry count: " + instance.getCount());
                        lock.unlock();
                        return true;
                    }
                }
            } catch (Exception e) {
                CUtils.logE(e);
            }
        }
        //delete local token and refresh_token
        removeTokens();
        flag.setFailure();
        count.decrementAndGet();
        CUtils.logD(TAG, "decrease retry count: " + instance.getCount());
        lock.unlock();
        CUtils.logD(TAG, "run: fail  notify ");
        return false;

    }

    private RefreshFlag getFlag() {
        return flag;
    }

    }
`

This is the flag

`
  
    public final class RefreshFlag {
    private static final int FLAG_SUCCESS = 0x01;
    private static final int FLAG_DOING = 0x11;
    private static final int FLAG_FAILURE = 0x10;
    private static final int FLAG_INIT = 0x00;
    /**
     * flag 标志位
     */
    private int flag = FLAG_INIT;

    public boolean isDoingLocked() {
        return flag == FLAG_DOING;
    }

    public void setDoing() {
        flag = FLAG_DOING;
    }

    public void setSuccess() {
        flag = FLAG_SUCCESS;
    }

    public void setFailure() {
        flag = FLAG_FAILURE;
    }

    public boolean isSuccess() {
        return flag == FLAG_SUCCESS;
    }

    public boolean isFailure() {
        return flag == FLAG_FAILURE;
    }

    public void resetFlag() {
        flag = FLAG_INIT;
    }
    }

`

-----------------------------

This is my way of achieving, I hope that you master educated us. Some friends also told me to use the reader-writer strategy to process tokens, but I don't know how to start.

I am Chinese and welcome to discuss with me in Chinese and English, even if my English is very bad.

**Comment by jpd236** [comment]
Hi,

Thanks for your interest in Volley! This forum is for reporting issues with Volley. It doesn't sound like you are encountering a bug - just that you would like to learn the best way to handle refreshing auth tokens when using it. If so, I would recommend another forum like StackOverflow or our Google Group (volley-users@googlegroups.com) which are meant for general questions.

At a glance - in general, the concept of detecting auth failures in a retry policy and using that to invalidate the auth token is exactly what I would do here. The rest seems like details of your application / auth mechanism. If it's standard OAuth then there are typically better libraries to handle this for you.

**Comment by wxz-Android** [comment]
Thank you for your reply.
It is indeed that I am not handling it properly and it is a problem for you. I will ask for some help on StackOverflow.
