### ISSUE TITLE
Changing Base Url at runtime

### ISSUE THREAD

**Issue by orhunkupeli** [google/volley#214]
Hi,

I'm now using Volley 1.1.1 and I would like to change base url at runtime. So, what is the best practice of doing it?

Thanks

**Comment by jpd236** [comment]
What is "base url" referring to? I'm not aware of such a concept in Volley.

It seems like you're generally asking for help using Volley - if so, please consider using a help forum like StackOverflow or our user group at volley-users@googlegroups.com. This is an issue tracker for reporting bugs with the library.
