### ISSUE TITLE
CtsUnofficialApisUsageTestCases failure on 1.1.0

### ISSUE THREAD

**Issue by SJPark04** [google/volley#218]
I got this error from CTS test, 

//test case
run cts -m CtsUnofficialApisUsageTestCases -t com.android.cts.api.UnofficialApisUsageTest#testNonApiReferences 

//error
Undefined type ref: org.apache.http.Header from: /myAPK.apk
Undefined type ref: org.apache.http.HttpEntity from: /myAPK.apk
Undefined type ref: org.apache.http.HttpResponse from: /myAPK.apk
Undefined type ref: org.apache.http.ProtocolVersion from: /myAPK.apk
Undefined type ref: org.apache.http.StatusLine from: /myAPK.apk
Undefined type ref: org.apache.http.client.HttpClient from: /myAPK.apk
Undefined type ref: org.apache.http.client.methods.HttpDelete from: /myAPK.apk
Undefined type ref: org.apache.http.client.methods.HttpEntityEnclosingRequestBase from: /myAPK.apk
Undefined type ref: org.apache.http.client.methods.HttpGet from: /myAPK.apk
Undefined type ref: org.apache.http.client.methods.HttpHead from: /myAPK.apk
Undefined type ref: org.apache.http.client.methods.HttpOptions from: /myAPK.apk
Undefined type ref: org.apache.http.client.methods.HttpPost from: /myAPK.apk
Undefined type ref: org.apache.http.client.methods.HttpPut from: /myAPK.apk
Undefined type ref: org.apache.http.client.methods.HttpTrace from: /myAPK.apk
Undefined type ref: org.apache.http.client.methods.HttpUriRequest from: /myAPK.apk
Undefined type ref: org.apache.http.entity.BasicHttpEntity from: /myAPK.apk
Undefined type ref: org.apache.http.entity.ByteArrayEntity from: /myAPK.apk
Undefined type ref: org.apache.http.message.BasicHeader from: /myAPK.apk
Undefined type ref: org.apache.http.message.BasicHttpResponse from: /myAPK.apk
Undefined type ref: org.apache.http.message.BasicNameValuePair from: /myAPK.apk
Undefined type ref: org.apache.http.message.BasicStatusLine from: /myAPK.apk
Undefined method ref: android.net.http.AndroidHttpClient.newInstance(java.lang.String)android.net.http.AndroidHttpClient from: /myAPK.apk
Undefined method ref: com.android.volley.toolbox.HttpClientStack.HttpPatch.addHeader(java.lang.String,java.lang.String)void from: /myAPK.apk
Undefined method ref: com.android.volley.toolbox.HttpClientStack.HttpPatch.setURI(java.net.URI)void from: /myAPK.apk

Undefined method ref: org.apache.http.Header.getName()java.lang.String from: /myAPK.apk
Undefined method ref: org.apache.http.Header.getValue()java.lang.String from: /myAPK.apk
Undefined method ref: org.apache.http.HttpEntity.getContent()java.io.InputStream from: /myAPK.apk
Undefined method ref: org.apache.http.HttpEntity.getContentLength()long from: /myAPK.apk
Undefined method ref: org.apache.http.HttpResponse.getAllHeaders()org.apache.http.Header[] from: /myAPK.apk
Undefined method ref: org.apache.http.HttpResponse.getEntity()org.apache.http.HttpEntity from: /myAPK.apk
Undefined method ref: org.apache.http.HttpResponse.getStatusLine()org.apache.http.StatusLine from: /myAPK.apk
Undefined method ref: org.apache.http.ProtocolVersion.&lt;init&gt;(java.lang.String,int,int) from: /myAPK.apk
Undefined method ref: org.apache.http.StatusLine.getStatusCode()int from: /myAPK.apk
Undefined method ref: org.apache.http.client.HttpClient.execute(org.apache.http.client.methods.HttpUriRequest)org.apache.http.HttpResponse from: /myAPK.apk
Undefined method ref: org.apache.http.client.methods.HttpDelete.&lt;init&gt;(java.lang.String) from: /myAPK.apk
Undefined method ref: org.apache.http.client.methods.HttpEntityEnclosingRequestBase.&lt;init&gt;() from: /myAPK.apk
Undefined method ref: org.apache.http.client.methods.HttpEntityEnclosingRequestBase.setEntity(org.apache.http.HttpEntity)void from: /myAPK.apk
Undefined method ref: org.apache.http.client.methods.HttpGet.&lt;init&gt;(java.lang.String) from: /myAPK.apk
Undefined method ref: org.apache.http.client.methods.HttpHead.&lt;init&gt;(java.lang.String) from: /myAPK.apk
Undefined method ref: org.apache.http.client.methods.HttpOptions.&lt;init&gt;(java.lang.String) from: /myAPK.apk
Undefined method ref: org.apache.http.client.methods.HttpPost.&lt;init&gt;(java.lang.String) from: /myAPK.apk
Undefined method ref: org.apache.http.client.methods.HttpPost.addHeader(java.lang.String,java.lang.String)void from: /myAPK.apk
Undefined method ref: org.apache.http.client.methods.HttpPost.setEntity(org.apache.http.HttpEntity)void from: /myAPK.apk
Undefined method ref: org.apache.http.client.methods.HttpPut.&lt;init&gt;(java.lang.String) from: /myAPK.apk
Undefined method ref: org.apache.http.client.methods.HttpPut.addHeader(java.lang.String,java.lang.String)void from: /myAPK.apk
Undefined method ref: org.apache.http.client.methods.HttpTrace.&lt;init&gt;(java.lang.String) from: /myAPK.apk
Undefined method ref: org.apache.http.client.methods.HttpUriRequest.getParams()org.apache.http.params.HttpParams from: /myAPK.apk
Undefined method ref: org.apache.http.client.methods.HttpUriRequest.setHeader(java.lang.String,java.lang.String)void from: /myAPK.apk
Undefined method ref: org.apache.http.entity.BasicHttpEntity.&lt;init&gt;() from: /myAPK.apk
Undefined method ref: org.apache.http.entity.BasicHttpEntity.setContent(java.io.InputStream)void from: /myAPK.apk
Undefined method ref: org.apache.http.entity.BasicHttpEntity.setContentLength(long)void from: /myAPK.apk
Undefined method ref: org.apache.http.entity.ByteArrayEntity.&lt;init&gt;(byte[]) from: /myAPK.apk
Undefined method ref: org.apache.http.message.BasicHeader.&lt;init&gt;(java.lang.String,java.lang.String) from: /myAPK.apk
Undefined method ref: org.apache.http.message.BasicHttpResponse.&lt;init&gt;(org.apache.http.StatusLine) from: /myAPK.apk
Undefined method ref: org.apache.http.message.BasicHttpResponse.setEntity(org.apache.http.HttpEntity)void from: /myAPK.apk
Undefined method ref: org.apache.http.message.BasicHttpResponse.setHeaders(org.apache.http.Header[])void from: /myAPK.apk
Undefined method ref: org.apache.http.message.BasicNameValuePair.&lt;init&gt;(java.lang.String,java.lang.String) from: /myAPK.apk
Undefined method ref: org.apache.http.message.BasicStatusLine.&lt;init&gt;(org.apache.http.ProtocolVersion,int,java.lang.String) from: /myAPK.apk

any idea for fix this issue?

**Comment by jpd236** [comment]
I see you also filed a CTS issue at https://issuetracker.google.com/113070388. I think that's probably the right place to track any potential fixes here, as I don't see what's wrong off hand.

You could probably work around this by following https://github.com/google/volley/wiki/Migrating-from-Apache-HTTP and making sure that you are not using any of the Apache HTTP portions of Volley (or elsewhere in your app), and then enabling proguard or another code optimizer to strip unused classes.
