### ISSUE TITLE
Unexpected response code 422

### ISSUE THREAD

**Issue by Slake07** [google/volley#221]
I am requesting for json response using below code:

       var jsnReq: VolleyJsonRequest = object : VolleyJsonRequest(Request.Method.GET, url, params,
                object : Response.Listener<JSONObject> {

                    override fun onResponse(response: JSONObject) {
                        var result = gson.fromJson(response.toString(), BikeListResponse::class.java)
                        callBack.onResponse(result)
                    }
                }, object : Response.ErrorListener {
            override fun onErrorResponse(error: VolleyError) {
                callBack.onError(error.networkResponse.statusCode, error.toString())
            }
        }) {
            @Throws(AuthFailureError::class)
            override fun getHeaders(): Map<String, String>? {
                return header
            }
        }
        MyApplication.instance!!.addToRequestQueue(jsnReq, tag)

I am getting error Unexpected response code 422 in call.

**Comment by jpd236** [comment]
That means the server is returning that error code, so I would recommend investigating the server logs to see why.

**Comment by kamal-dev** [comment]
@Slake07 I am having the same issue while working on my project. Can you help me out regarding how to solve this problem? 
Thank You.

**Comment by daedaesplayground1991** [comment]
Please explain the details of your issue and the project that your
currently working on So that I may help you troubleshoot the issue and
figure out how you might best solve it and the best way to apply it to
doing the project as well.

daedaesplayground

**Comment by Slake07** [comment]
@kamal-dev I don't remember exactly now. But i think it because of parameters you are passing in it. how you are passing?
