### ISSUE TITLE
Unexpected response code 200 - Emulator - gzip response 

### ISSUE THREAD

**Issue by CassBurn** [google/volley#222]
Hello,

In toolbox.BasicNetwork.java (Volley 1.1.1) NetworkResponse (L.212) log me this error:
[130] BasicNetwork.performRequest: Unexpected response code 200

It appen only on Emulator with a gzip response (work correctly on device).
If the server don't send a gzip response, the response will work.

On emulator, httpResponse.getContentLength() return -1 

Did anyone have a workaround ?

Cheers

**Comment by jpd236** [comment]
Looks similar to #92. Please take a look there and reopen if you believe you are encountering a different issue.
