### ISSUE TITLE
Successful Response but nothing in onResponse(response) -> response variable

### ISSUE THREAD

**Issue by selmansavas** [google/volley#224]
I am doing a post request successfully, and on onResponse function i try to get the body of the response, which is a JSONObject, and returning value is like this _{"GetDataResult":"Access Granted"}_. But when i try to get the data via response variable, there is nothing in there. I think i am using it wrong, or is this a bug? Thanks a lot in advance

**Comment by jpd236** [comment]
Unless there's something very special with your app/server, it seems unlikely to be a bug. But there's not really any way for us to look into it without more information.

What I'd recommend you do is post your question on a help forum, like StackOverflow or our user group at volley-users@googlegroups.com, along with some sample code that demonstrates the problem you're having. Hopefully you'll either get an answer to your question, or it will be clearer that you indeed have a bug, and you can reopen this with more details on why that is. If you do reopen it, sample code would be strongly preferable, along with information about what version of Volley and the Android platform you're using, so we can reproduce whatever you're seeing.
