### ISSUE TITLE
Support for latest API level

### ISSUE THREAD

**Issue by ebghrimtech** [google/volley#225]
Hello,

We are currently using Volley in one of our applications. Actually we need a favour from your side. According to the Google Play Policy, all apps have to provide support for at least API level 26. It seems like yours is not as per the new Google Play Policy. We are targeting API level 28. So can you please provide us support for API level 28 in your current repository?

**Comment by jpd236** [comment]
Are you having a specific problem? I'm not aware of anything preventing apps from using Volley and targeting API 28.

**Comment by ebghrimtech** [comment]
Thank you for your response.
We are not having any issues as of now. According to the Google Play Policy, we have to make sure that our app, including all the dependencies used, targets at least API level 26 according to the [Android Official Docs.](https://developer.android.com/distribute/best-practices/develop/target-sdk#check_and_update_your_sdks_and_libraries) Thus, we have contacted you to make sure that it won't cause any problems.

**Comment by jpd236** [comment]
Got it, thank you for the clarification and link.

There should be no problem using Volley w/ apps that target API level 26 or higher (and there are plenty of apps I know that do exactly this). At the moment I don't think we should set the targetSdkVersion explicitly in our manifest as it's not a requirement either, but if we get lots of inquiries along these lines then it's something we can consider.
