### ISSUE TITLE
Error: Program type already present: com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable

### ISSUE THREAD

**Issue by ykishor10** [google/volley#239]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "in.co.cashchat.cashchat"
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation files('libs/YouTubeAndroidPlayerApi.jar')
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    //noinspection GradleCompatible
    implementation 'com.google.android.gms:play-services-location:16.0.0'
    //noinspection GradleCompatible
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.google.android.gms:play-services-ads:17.1.0'
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.mcxiaoke.volley:library:1.0.19'
    implementation 'com.github.chrisbanes.photoview:library:1.2.3'
    implementation 'com.facebook.android:facebook-android-sdk:4.37.0'
    implementation 'com.pkmmte.view:circularimageview:1.1'
    implementation 'com.melnykov:floatingactionbutton:1.3.0'
    implementation 'com.squareup.okhttp:okhttp:2.5.0'
    implementation 'com.github.bumptech.glide:glide:4.7.1'
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:28.0.0'
    //noinspection GradleCompatible
    implementation 'com.android.support:design:28.0.0'
    //noinspection GradleCompatible
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    //noinspection GradleCompatible
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.github.bumptech.glide:glide:4.7.1'
    implementation 'com.balysv:material-ripple:1.0.2'
    implementation 'com.google.firebase:firebase-core:16.0.4'
    implementation 'com.google.firebase:firebase-ads:17.0.0'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'
    implementation 'com.google.android.gms:play-services-gcm:16.0.0'
    implementation 'com.google.android.gms:play-services-ads:17.1.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.android.volley:volley:1.1.0'
    implementation 'net.vrallev.android:cat:1.0.5'
    implementation files('libs/YouTubeAndroidPlayerApi.jar')
    implementation files('libs/AppnextAndroidSDKCore.aar')
    implementation files('libs/AppnextAndroidSDKAds.aar')
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support',  module: 'support-annotations'
    })
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:support-annotations:28.0.0'
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.5@aar') {
        transitive = true
    }
}
apply plugin: 'com.google.gms.google-services'
``

**Comment by jpd236** [comment]
That error generally means you have two dependencies that are both providing the same class, causing a conflict. Skimming your gradle rules I see at least two copies of Volley from:

implementation 'com.mcxiaoke.volley:library:1.0.19'
implementation 'com.android.volley:volley:1.1.0'

You can only use one of these or the other. Make sure your dependencies only pull in one copy of the library.
