### ISSUE TITLE
Can I send String body in the DELETE REQUEST?

### ISSUE THREAD

**Issue by mudassirzulfiqar** [google/volley#24]

**Comment by xesam** [comment]
no. but you can provider a different "HttpStack" to support DELETE body.

**Comment by johneke** [comment]
It seems like adding a body to DELETE requests was deliberately skipped. If someone wouldn't mind explaining the rationale behind it, I'd really appreciate it, just curious :)

**Comment by jpd236** [comment]
As far as I can tell HttpUrlConnection itself doesn't allow it, so you'd have to ask Java creators :)

Seems like it's kind of undefined behavior, e.g. https://tools.ietf.org/html/rfc7231#section-4.3.5, but if HttpUrlConnection doesn't support it then there's not much Volley can do.

**Comment by johneke** [comment]
Gotcha. I figured it was something along those lines. Thanks a lot @jpd236!
