### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV) in Okhttp

### ISSUE THREAD

**Issue by c0d3er** [google/volley#241]
For more details plese check here: https://stackoverflow.com/questions/53511336/a-libc-fatal-signal-11-sigsegv-in-okhttp

Stacktrace:
```    [OkHttp] sendRequest<<
I/System.out: Wrong owner. Perhaps a late disconnect
I/Choreographer: Skipped 39 frames!  The application may be doing too much work on its main thread.
I/System.out: [OkHttp] sendRequest>>
I/System.out: [OkHttp] sendRequest<<
I/System.out: Wrong owner. Perhaps a late disconnect
I/Choreographer: Skipped 39 frames!  The application may be doing too much work on its main thread.
I/System.out: [OkHttp] sendRequest>>
    [OkHttp] sendRequest<<
I/System.out: Wrong owner. Perhaps a late disconnect
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x6d080000 in tid 22280 (p.tamilstickers)
Application terminated.```

**Comment by jpd236** [comment]
This doesn't seem like a Volley issue as we're just invoking the underlying HTTP APIs. Either way, your log snippet doesn't include any information about the native crash - there should be a full native stack dump associated with it that may be helpful.

To see if this is somehow a Volley issue, we'd want more details. For example, could you try just using the underlying HTTP library directly (OkHttp if you're using an OkHttp-based HTTP stack, or HttpUrlConnection if you're using HurlStack)? Can you provide a small sample app that demonstrates the problem? What version(s) of Android, and on which device? If so, we can reopen and look further.
