### ISSUE TITLE
Program type already present: com.google.android.youtube.player.YouTubeApiServiceUtil

### ISSUE THREAD

**Issue by dheerajsinghrathore** [google/volley#245]
//Build file of Project module

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.2.0'
    }
}

allprojects {
    repositories {
        jcenter()
        google()
        maven { url "https://maven.google.com/"}
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

// I am using a library and build file of this libary is ;

apply plugin: 'com.android.library'
//apply plugin: 'com.novoda.bintray-release'

android {
    compileSdkVersion 28

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 4
        versionName "1.2.1"
    }
    lintOptions {
        abortOnError false
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:support-annotations:28.0.0'
    implementation 'com.thefinestartist:finestwebview:1.2.7'
}

//Build file of (Module:app)

apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    useLibrary 'org.apache.http.legacy'
    buildToolsVersion '28.0.3'
    defaultConfig {
        applicationId "com.milkyway.watchnearn"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0.0"

        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
    }
}

// Maven Repositories
repositories {

    google()
    mavenCentral()
    flatDir { dirs 'libs' }

}

dependencies {

    // test Libraries
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    testImplementation 'junit:junit:4.12'

    // Android Support Libraries
    //noinspection GradleCompatible
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:mediarouter-v7:28.0.0'
    implementation 'com.android.support:support-vector-drawable:28.0.0'
    implementation 'com.android.support:support-annotations:28.0.0'
    // Adnetwork Libraries
    implementation 'com.startapp:inapp-sdk:3.6.2'

    // MultiDex Dependency
    implementation 'com.android.support:multidex:1.0.3'

    // Other Libraries
    implementation project(':library')
    implementation 'com.squareup.okio:okio:1.15.0'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.nineoldandroids:library:2.4.0'
    implementation 'com.squareup.okhttp3:okhttp:3.12.0'
    //Youtube Video
    implementation 'com.thefinestartist:finestwebview:1.2.7'
    implementation files('libs/YouTubeAndroidPlayerApi.jar')

    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'de.hdodenhof:circleimageview:2.2.0'
    implementation 'com.mcxiaoke.volley:library:1.0.19'
    implementation 'com.github.d-max:spots-dialog:1.1@aar'
    implementation 'com.github.paolorotolo:appintro:4.1.0'
    implementation 'org.apache.httpcomponents:httpclient-android:4.3.5'
    implementation 'com.facebook.network.connectionclass:connectionclass:1.0.1'
    implementation 'com.google.android.gms:play-services-tagmanager:16.0.5'
    // slider library
    implementation 'com.daimajia.slider:library:1.1.5@aar'
    implementation 'com.google.apis:google-api-services-youtube:v3-rev206-1.25.0'
    // Google Libraries
    implementation 'com.google.android.gms:play-services-analytics:16.0.5'
    implementation 'com.google.android.gms:play-services-gcm:16.0.0'
    implementation 'com.google.android.gms:play-services-ads:17.1.1'
    implementation 'com.google.android.gms:play-services-auth:16.0.1'

    // Firebase
//    implementation 'com.google.firebase:firebase-ads:17.1.1'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'
    implementation 'com.google.firebase:firebase-core:16.0.5'
    implementation 'com.google.firebase:firebase-auth:16.0.5'
}

apply plugin: 'com.google.gms.google-services'

**Comment by mukeshkumar619** [comment]
@dheerajsinghrathore did you find anything?
