### ISSUE TITLE
use a self signed certificate with volley requests

### ISSUE THREAD

**Issue by MahdiTaghipour** [google/volley#254]
how to use a self signed certificate with volley requests?
i have the 1.1.0 version of volley.
i have used guides of [this ](https://blog.applegrew.com/2015/04/using-pinned-self-signed-ssl-certificate-with-android-volley/)link but i get error "javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found."

**Comment by jpd236** [comment]
This doesn't seem like a Volley issue but rather an issue with the certificate you've configured. The blog post you linked has exactly this error as the first comment along with a suggestion on how to resolve it. I would suggest following up there.
