### ISSUE TITLE
how to Pause/Resume DownloadRequest ?

### ISSUE THREAD

**Issue by Nightprince** [google/volley#257]
how to Pause/Resume DownloadRequest on volley ?

RequestQueue.stop(); eliminates the request altogether and can not continue with RequestQueue.start();

**Comment by jpd236** [comment]
Unfortunately Volley does not support pausing in-flight requests. Please see https://github.com/google/volley/wiki/Frequently-Asked-Questions#why-doesnt-volley-support-large-downloadsuploads for more details on why Volley isn't suited for the kinds of (large) requests that would merit pause/resume support.
