### ISSUE TITLE
Volley is not sending new Request after manually change the time if the app is open

### ISSUE THREAD

**Issue by Aabauser** [google/volley#260]
If my app is open and manually change time (backward or forwards), volley is not requesting new requests it hits already hit request and response also already in the cache is returning. if I clear cache and data then only the new request will send and new response will come. How the volley requests are related to system time and why this is happening? Is there any solution for this?

**Comment by jpd236** [comment]
Time is checked here:

https://github.com/google/volley/blob/master/src/main/java/com/android/volley/Cache.java#L103

Your HTTP response ostensibly includes a timestamp indicating the cache expiration time of the response. So we compare it to the system time to decide if the entry is expired or not.

This seems like it's working as expected to me. What behavior would you expect when the server indicates an expiration time for an HTTP response and the device time is prior to then?
