### ISSUE TITLE
BasicNetwork.java throw NPE

### ISSUE THREAD

**Issue by mingfudu** [google/volley#263]
https://github.com/google/volley/blob/master/src/main/java/com/android/volley/toolbox/BasicNetwork.java#L293

Method threw 'java.lang.NullPointerException' exception. Cannot evaluate com.android.volley.toolbox.PoolingByteArrayOutputStream.toString()

i get a NPE when use MockWebServer to mock a post request 

```java
server = new MockWebServer();
    final Dispatcher dispatcher = new Dispatcher() {

      @Override public MockResponse dispatch(RecordedRequest request) {
        switch (request.getPath()) {
          case "/api/xxx/xx":
            return new MockResponse().setResponseCode(500).setBody("bad request");
          case "/api/xx":
            return new MockResponse().setResponseCode(200).setBody("version=9");
          default:
            return new MockResponse().setResponseCode(404);
        }
      }
    };

    server.setDispatcher(dispatcher);```

**Comment by jpd236** [comment]
The line of code you linked is calling `PoolingByteArrayOutputStream#toByteArray`, not toString. So I don't see how you could have seen a crash there due to that code.

There's not really enough information for us to reproduce this. Can you provide a fully-working sample, along with the _full_ stack trace (including line numbers)?

**Comment by mingfudu** [comment]
PoolingByteArrayOutputStream#toByteArray do not throw NPE exactly. I got a NPE after ExecutorDelivery#postError. When i debug it using android studio i found after bytes.close() 
bytes value just changed to "Method threw 'java.lang.NullPointerException' exception. Cannot evaluate com.android.volley.toolbox.PoolingByteArrayOutputStream.toString()". Maybe  the debugger cannot get value of bytes so it throw a error. Please close the issue. thanks a lot!
