### ISSUE TITLE
Volley return null on release variant

### ISSUE THREAD

**Issue by mortalwind** [google/volley#269]
Volley works properly on debug variant but when on release variant, Volley return null response.
I've added this in proguard-rules:
-dontwarn org.apache.http.**
-dontwarn android.net.http.AndroidHttpClient
-dontwarn com.google.android.gms.**
-dontwarn com.android.volley.toolbox.**
-keep class com.android.volley.** { *; }

I'm using  volley:1.1.1, gson:2.8.5, gradle version 3.

**Comment by xword-machine-user** [comment]
In general, Volley works fine with Proguard, so we would likely need more info about your specific scenario to know why you're encountering failures. If you can provide a sample app and clarify exactly where you're seeing null, that would be helpful.

If I had to guess, GSON uses reflection to instantiate classes, so you almost certainly need to add special configuration to keep those classes to be able to parse responses with them, independent of anything to do with Volley. Google for "Gson proguard" to see some example configurations that might be necessary.

**Comment by jpd236** [comment]
In general, Volley works fine with Proguard, so we would likely need more info about your specific scenario to know why you're encountering failures. If you can provide a sample app and clarify exactly where you're seeing null, that would be helpful.

If I had to guess, GSON uses reflection to instantiate classes, so you almost certainly need to add special configuration to keep those classes to be able to parse responses with them, independent of anything to do with Volley. Google for "Gson proguard" to see some example configurations that might be necessary.

**Comment by mortalwind** [comment]
`String url = KaliteApiPath + "/SonKontrolTeyit";


            StringRequest stringRequest = new StringRequest(Request.Method.POST, url,
                    new Response.Listener<String>() {
                        @Override
                        public void onResponse(String response) {
                            Gson gson = new Gson();
                            SonKontrolResponse apiResponse = gson.fromJson(response, SonKontrolResponse.class);

                            int code = apiResponse.getCode();

                            if (code == 200) {

                                txtSonuc.setText( txtSeriNo.getText().toString().trim() + " -Teyit: OK"+ "\r\n" + txtSonuc.getText());

                            } else {
                                txtSonuc.setText( txtSeriNo.getText().toString().trim() + "- " + apiResponse.getResult() + "\r\n" + txtSonuc.getText());
                            }
                            txtSeriNo.setText("");
                            if (dialog.isShowing()) {
                                dialog.dismiss();
                            }
                        }
                    },
                    new Response.ErrorListener() {
                        @Override
                        public void onErrorResponse(VolleyError error) {
                            Toast.makeText(UretimTeyitF1Activity.this, error.toString(), Toast.LENGTH_LONG).show();
                        }
                    }) {
                @Override
                protected Map<String, String> getParams() {
                    Map<String, String> params = new HashMap<String, String>();
                    params.put("PersonelNo", txtPersonelNo.getText().toString());
                    params.put("SeriNo", txtSeriNo.getText().toString().trim());
                    params.put("IslemNo", islemKodu);
                    params.put("TerminalNo", deviceID);
                    return params;
                }

            };
            stringRequest.setRetryPolicy(new DefaultRetryPolicy(
                    5000,
                    DefaultRetryPolicy.DEFAULT_MAX_RETRIES,
                    DefaultRetryPolicy.DEFAULT_BACKOFF_MULT));
            RequestQueue requestQueue = Volley.newRequestQueue(UretimTeyitF1Activity.this);
            requestQueue.add(stringRequest);`
there is my code. But I can't send sample app because my API works internal. 
I send some files as zip below:
[volleyproblem.zip](https://github.com/google/volley/files/3130145/volleyproblem.zip)

**Comment by jpd236** [comment]
Unfortunately then it's going to be challenging for us to diagnose what's happening here.

The proguard-rules.pro rule has some Gson rules but I don't see an uncommented line that corresponds to keeping the data model classes (SonKontrolResponse in your snippet). It's also missing the following rules from the gson repository:

-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

which might be relevant.

Otherwise, what's actually null - "response" as passed to onResponse? Or something else?

**Comment by mortalwind** [comment]
I will try add those classes and my model class as "-keep". I get string response "NULL" on onResponse.

**Comment by mortalwind** [comment]
Sorry guys, I found the problem. When I  commented GSON lines on my code like that:
`// Gson gson = new Gson();
 // IslemNoResponse apiResponse = gson.fromJson(response, IslemNoResponse.class);
Toast.makeText(UretimTeyitF1Activity.this, response, Toast.LENGTH_SHORT).show();`
Activity gets response as JSON properly.  I think GSON can't deserialize to object from Json. I've changed my proguard.pro, the file content is below:

-dontwarn org.apache.http.**
-dontwarn android.net.http.AndroidHttpClient
-dontwarn com.google.android.gms.**
-dontwarn com.android.volley.toolbox.**
-keep class com.android.volley.** { *; }

##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Application classes that will be serialized/deserialized over Gson
-keep class com.google.gson.examples.android.model.** { *; }

# Prevent proguard from stripping interface information from TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Application classes that will be serialized/deserialized over Gson
 -keep public class com.alce.alcemobileapp.PersonelInfoResponse
 -keep public class com.alce.alcemobileapp.IslemNoResponse
 -keep public class com.alce.alcemobileapp.SonKontrolResponse

##---------------End: proguard configuration for Gson  ----------

**Comment by jpd236** [comment]
Great, yes, since Gson relies on reflection the classes can't be obfuscated/removed by Proguard.

**Comment by mortalwind** [comment]
Thanks guys.
