### ISSUE TITLE
Volley variant for Desktop Java. I know this might look dumb. But i would like to know if you have developped a Volley variant for Desktop Java. Thanks

### ISSUE THREAD

**Issue by francisnnumbi** [google/volley#270]

**Comment by jpd236** [comment]
It's a fair question. We do not support desktop VMs as doing so would introduce significantly more complexity into Volley's architecture and implementation. There are concepts like the main thread and various utilities for URI/text processing that would need to be abstracted away, and we would rather keep Volley simpler by focusing on the Android platform for the foreseeable future.
