### ISSUE TITLE
Image is not cropping when using ScaleType CENTER_CROP 

### ISSUE THREAD

**Issue by haggai** [google/volley#273]
example : 
on xml : 
```
<com.android.volley.toolbox.NetworkImageView
		android:layout_width="100dp"
		android:layout_height="100dp"
		android:scaleType="centerCrop"/>
```

and set the image url to:
`"https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/20130330_-_Vannes_Volley-Ball_-_Terville_Florange_Olympique_Club_-_054.jpg/1200px-20130330_-_Vannes_Volley-Ball_-_Terville_Florange_Olympique_Club_-_054.jpg"
`

The resulted image is not cropped to square and it keeps the aspect ratio of the original image.

I think the bug may be in this code in ImageRequest.java : 
```
// If necessary, scale down to the maximal acceptable size.
            if (tempBitmap != null
                    && (tempBitmap.getWidth() > desiredWidth
                            || tempBitmap.getHeight() > desiredHeight)) {
                bitmap = Bitmap.createScaledBitmap(tempBitmap, desiredWidth, desiredHeight, true);
                tempBitmap.recycle();
            } else {
                bitmap = tempBitmap;
            }
```
I think maybe it was supposed to use mMaxWidth/mMaxHeight instead of desiredWidth/desiredHeight.
Thanks

**Comment by jpd236** [comment]
On my test device (Pixel 3 running Android P) it looks exactly like I'd expect:

![device-2019-05-20-174622](https://user-images.githubusercontent.com/4713321/58060658-3a166d00-7b27-11e9-8af4-bd93019118ff.png)

We'd need more information to look at what might be going wrong for you - e.g. a fully functioning sample app and more information about your test environment (emulator vs real device? which SDK level)?

One thing I might suggest trying would be to download the image and embed it with the test APK and then just use it with a vanilla ImageView. If you're still seeing the problem then it's a problem with your app (or with ImageView), not with Volley.

**Comment by jpd236** [comment]
Closing without additional info from the reporter - please reopen with the requested details if you think there's a bug here.
