### ISSUE TITLE
Request Method being changed once I send to server. 

### ISSUE THREAD

**Issue by Salim1993** [google/volley#275]
Hello, im having weird  issues with the Request method being changes when I send my request to the server.  using volley version : com.android.volley:volley:1.1.1

I set a POST method to the server,but the method on thee server is reading it as GET. This happens when i change form staging to production server. Method stays as POST when I'm on staging, and works correctly.

Not too sure where to begin to look into to be able to debug and solve this issue.  Used debugger to check the object right before i add it to volley queue. Says Method assigned is 1 which is supposed to be POST method.

**Comment by jpd236** [comment]
If all that's changing between the successful scenario and the unsuccessful scenario is the server environment you're using, wouldn't that suggest the issue is on the server side?

**Comment by Salim1993** [comment]
Yeah, I guess so, but we troubleshooting between the server. Just hoping for some info or tips, but I guess not Ill just close this ticket until later and we have more info to be able to troubleshot, I guess.

**Comment by jpd236** [comment]
Sorry about that, but yeah, I'm not sure there's much we'd be able to help here. As long as the method is POST, the HttpStack should be setting that request method on the underlying request. If you find that you're able to pin this down to an issue in Volley, please let us know with more details on the code in question.
