### ISSUE TITLE
how can i close connection 

### ISSUE THREAD

**Issue by Saurav-Suman** [google/volley#276]
I am not able to close the connection which is initiated and due to this my backend server connection pool is increased and i am getting bellow error for some requests and when load is high.

Error =>com.android.volley.NoConnectionError: java.net.ConnectException: Failed to connect to IP:443 :: Message =>java.net.ConnectException: Failed to connect to IP:443

**Comment by jpd236** [comment]
As of Volley 1.1.1 we do close the HttpUrlConnection when you are using HurlStack:

https://github.com/google/volley/commit/62c19019e43a76ba4a084b25548e7fb1cfd4a457#diff-7b52a41e4e3e2e1401e6486bee665d19

If you're not observing this behavior, we will need more details about your app, the version of Volley you are using, the HttpStack you are using, and ideally some sample code which exhibits the issue.

**Comment by Saurav-Suman** [comment]
@jpd236 We are using  Volley 1.1.0 and we are also using HurlStack.

`mRequestQueue = Volley.newRequestQueue(AppController.getInstance(), new HurlStack(null, pinnedSSLSocketFactory()));`

**Comment by jpd236** [comment]
OK, can you try updating to 1.1.1? There was a bug fix in that release related to closing connections in HurlStack. (#138).

**Comment by Saurav-Suman** [comment]
Thanks man
