### ISSUE TITLE
ERROR- com.android.volley.ClientError

### ISSUE THREAD

**Issue by Alireza-hr** [google/volley#278]
when im trying to send my data to server i get message from onErrorResponse 
com.android.volley.ClientError 

what mean ? 

its my Code : 

               Volley.newRequestQueue(getContext()).add(new StringRequest(Request.Method.PUT, 
               ConstApiLinks.box.toString() ,
                s -> {

                    try {

                        JSONObject jsonObject = new JSONObject(s);
                        if (jsonObject.getString("msg").equals("Device successfully added to customer")) {

                        } else {
                            result.onError("");
                        }
                    } catch (JSONException e) {
                        e.printStackTrace();
                    }
                  =               }, volleyError -> {
                   String errorCode;
                    Log.d("ERROR_VOLLY", volleyError.toString() + volleyError.getMessage());

                    NetworkResponse networkResponse = volleyError.networkResponse;
                    if (networkResponse != null) {
                errorCode = String.valueOf(networkResponse.statusCode);
            } else {
                errorCode = "0";
            }
            result.onError(errorCode);
        }
        ) {
            @Override
            public Map<String, String> getHeaders() {
                Map<String, String> params = new HashMap<>();
                params.put("Content-Type", "application/json");
                params.put("Authorization", "Bearer " + Utils.readSharedSetting(context, "access_token", ""));
                return params;
            }
        });

**Comment by jpd236** [comment]
It means the server returned a 4xx error code.

https://github.com/google/volley/blob/d1a3d5388c79ff1a6fdb904daeff9b39d0bb7d26/src/main/java/com/android/volley/toolbox/BasicNetwork.java#L199

**Comment by KishorMorais** [comment]
@Alireza-hr have you got the error cleared?
  i'm also having the same error...

**Comment by KishorMorais** [comment]
@Alireza-hr Could you please explain me how to solve this issue?

**Comment by gayanramyakumara** [comment]
same issue.anyone can  help ?

**Comment by sivapriyavn** [comment]
same issue with me can anyone tel how to resolve the android.volley.clienterror

**Comment by s5103720KG** [comment]
the same issue can help?

**Comment by Harsh0021** [comment]
Hey!!
I solved out the problem:
Change this code -
`{
        @Override
        public Map<String, String> getHeaders() {
            Map<String, String> params = new HashMap<>();
            params.put("Content-Type", "application/json");
            params.put("Authorization", "Bearer " + Utils.readSharedSetting(context, "access_token", ""));
            return params;
        }`
with this:
{
        @Override
        public Map<String, String> getParams() throws AuthFailureError{
            Map<String, String> params = new HashMap<>();
            params.put("Content-Type", "application/json");
            params.put("Authorization", "Bearer " + Utils.readSharedSetting(context, "access_token", ""));
            return params;
        }

then it will work fine.
Thank you!!

**Comment by manjirikolte** [comment]
can you tell me what is Utils

**Comment by Alireza-hr** [comment]
@manjirikolte 
Hi :-)
I always create a shared Utils class for the most commonly used function.

**Comment by MoustafaElsaghier** [comment]
in my case i was missing some parameters required to be send but, it must be more clear for us
