### ISSUE TITLE
NetworkImageView cannot be disabled and pops over other content

### ISSUE THREAD

**Issue by Goevex** [google/volley#281]
When setting NetworkImageView.isEnabled(false) it is not greyed out or something like this. It still seems to be enabled. Furthermore it is drawn over content which is placed above (e.g. TextView)

**Comment by jpd236** [comment]
NetworkImageView is no different from ImageView, which it extends, in terms of how it handles the enabled state. If you want different state for disabled ImageViews, that's something you'd need to implement yourself - same as if you were rendering a bundled image in ImageView directly.
