### ISSUE TITLE
Cache header `If-Modified-Since` does not conform to RFC1123

### ISSUE THREAD

**Issue by stonecauldron** [google/volley#287]
In `BasicNetwork.java` cache headers are automatically populated before a request is performed.

When required, the `If-Modified-Since` header is filled with the date of the last modification in the method `getCacheHeaders`.

The format used for the date, however, does not respect RFC1123 since it includes the name of the timezone (`GMT`) as well as the offset e.g. 
`Tue, 27 Aug 2019 07:36:17 GMT+00:00`.

If we follow the [RFC1123 grammar](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.3.1) defined below:
```
HTTP-date    = rfc1123-date | rfc850-date | asctime-date
rfc1123-date = wkday "," SP date1 SP time SP "GMT"
rfc850-date  = weekday "," SP date2 SP time SP "GMT"
asctime-date = wkday SP date3 SP time SP 4DIGIT
date1        = 2DIGIT SP month SP 4DIGIT
                      ; day month year (e.g., 02 Jun 1982)
date2        = 2DIGIT "-" month "-" 2DIGIT
                      ; day-month-year (e.g., 02-Jun-82)
date3        = month SP ( 2DIGIT | ( SP 1DIGIT ))
                      ; month day (e.g., Jun  2)
time         = 2DIGIT ":" 2DIGIT ":" 2DIGIT
                      ; 00:00:00 - 23:59:59
wkday        = "Mon" | "Tue" | "Wed"
                    | "Thu" | "Fri" | "Sat" | "Sun"
weekday      = "Monday" | "Tuesday" | "Wednesday"
                    | "Thursday" | "Friday" | "Saturday" | "Sunday"
month        = "Jan" | "Feb" | "Mar" | "Apr"
                    | "May" | "Jun" | "Jul" | "Aug"
                    | "Sep" | "Oct" | "Nov" | "Dec"
```
We see that the RFC1123 format does not support a timezone offset after the timezone designation. (`rfc1123-date = wkday "," SP date1 SP time SP "GMT"`)

As such, volley should format the previously shown date as `Tue, 27 Aug 2019 07:36:17 GMT` without any offset after the GMT designation.

**Comment by stonecauldron** [comment]
Thank you for getting back to me.

I do not have access to a physical device; I am running this on an emulator whose settings I have appended to the end of the post.

When I run the snippet of code you wrote I get the following output:
```
E/TEST: Thu, 29 Aug 2019 02:24:42 GMT+00:00
```

So for some reason, on my emulator the `+00:00` is appended but I don't really have a way to explain why this behaviour is inconsistent across platforms.

Nevertheless, I believe replacing the format string by `EEE, dd MMM yyyy HH:mm:ss 'GMT'` could be a good solution.  It would make no difference to the cases that are already working while also preventing platform-specific idiosyncrasies of how the `zzz` format is transcribed to affect the correctness of the output.

As a side note, others seem to have faced a similar problem as evidenced by this [stackoverflow question](https://stackoverflow.com/questions/37098453/valueerror-unconverted-data-remains-0000/37100255#37100255).

```


Name: Samsung_Tab_A_9.7_API_24

CPU/ABI: Google APIs Intel Atom (x86)

Path: /Users/cauldron/.android/avd/Samsung_Tab_A_9.7_API_24.avd

Target: google_apis [Google APIs] (API level 24)

Skin: 1024x768

SD Card: 512 MB

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: Samsung Tab A 9.7

hw.lcd.width: 768

hw.initialOrientation: landscape

image.androidVersion.api: 24

tag.id: google_apis

hw.mainKeys: yes

hw.camera.front: emulated

avd.ini.displayname: Samsung Tab A 9.7 API 24

hw.gpu.mode: auto

hw.ramSize: 1536

PlayStore.enabled: false

fastboot.forceColdBoot: no

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 1024

vm.heapSize: 48

skin.dynamic: yes

hw.device.manufacturer: User

hw.gps: yes

skin.path.backup: _no_skin

hw.audioInput: yes

image.sysdir.1: system-images/android-24/google_apis/x86/

showDeviceFrame: no

hw.camera.back: virtualscene

AvdId: Samsung_Tab_A_9.7_API_24

hw.lcd.density: 120

hw.arc: false

hw.device.hash2: MD5:5a81da80da648bc3358efc502a0c9d0a

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google APIs

runtime.network.latency: none

disk.dataPartition.size: 800M

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes
```

**Comment by jpd236** [comment]
Thanks for the report. I was able to reproduce on an API 24 emulator. Strange behavior difference but easy enough to work around per your suggestion.

**Comment by stonecauldron** [comment]
Thank *you* for fixing the issue so quickly 👍
