### ISSUE TITLE
How can we use beta version of volley right now

### ISSUE THREAD

**Issue by DroidPulkit** [google/volley#300]
As most libraries provide a way to get beta version, it makes sense for Volley to add this also.
And I guess, I am facing issues in 1.1.1, because we don't have AndroidX support. Any way, we can use the beta version of the 2.0.0 Right now.

**Comment by jpd236** [comment]
Posted instructions for how to use our snapshot builds at https://github.com/google/volley/wiki/Frequently-Asked-Questions#how-can-i-use-prerelease-versions-of-volley.
