### ISSUE TITLE
volley good response on emulator but error on phone

### ISSUE THREAD

**Issue by gozh234** [google/volley#306]
hi im trying to connect to a server including register loging and updating profile every thing works fine in emulator but posting one of apis for updating profilr keeps showing clienterror on the phone
emulature ok but phone showing onError

**Comment by jpd236** [comment]
There's not enough information here for us to be able to look further into this. My recommendation would be to look at the server-side logs (assuming you have access to them) to see what is different about the requests being invoked on emulator vs. on real device. Ultimately all Volley does is serve as a helper layer on top of another HTTP stack like HttpUrlConnection or Apache's HttpClient, so I would dig into what is happening differently at that level.

If you'd like us to look further into this, we'd need to know more details like:

- What is the nature of the request that's failing?
- What version of Volley are you using?
- What version of emulator, and what Android device / version for the physical device?
- Ideally, can you provide a sample app that demonstrates the problem?
