### ISSUE TITLE
Dns support 

### ISSUE THREAD

**Issue by Jparrgam** [google/volley#307]
Hi, volley support changes dns ?

**Comment by jpd236** [comment]
Volley doesn't have any specific functionality around changing the DNS server, assuming that's what you mean. It would depend on the underlying HTTP stack.

From a quick search, it doesn't appear that HttpUrlConnection supports a custom DNS server, so HurlStack wouldn't either. Apache HTTP seems like it does (e.g. https://stackoverflow.com/questions/24350150/how-to-override-dns-in-http-connections-in-java), so you could use that, although that library is deprecated on newer versions of Android. You could also make a custom BaseHttpStack using another HTTP library which supports DNS changes, e.g. OkHttp.
