### ISSUE TITLE
Volley cannot display Unicode strings correctly?

### ISSUE THREAD

**Issue by anta40** [google/volley#309]
I'm using Volley 1.1.1.
The JSON I want to parse is available at: https://api.banghasan.com/quran/format/json/surat

You'll notice that the field **asma** contains Arabic values. Here's my JSON parsing code:
```
 StringRequest stringRequest = new StringRequest(Request.Method.GET, SURAT_API_URL,
                new Response.Listener() {
                    @Override
                    public void onResponse(Object response) {

                        String resp = response.toString();
                        try {
                            JSONObject rawJSONObject = new JSONObject(resp);
                            JSONArray hasil = rawJSONObject.getJSONArray("hasil");

                            int len = hasil.length();

                            for (int x = 0; x < len; x++){
                                JSONObject obj = hasil.getJSONObject(x);
                                System.out.println("Asma: "+obj.getString("asma"));
                                edit_text.append("Asma: "+obj.getString("asma")+"\n");
                            }
                        }
                        catch (JSONException je){

                        }

                    }},
                new Response.ErrorListener() {
                    @Override
                    public void onErrorResponse(VolleyError error) {
                    // txtView.setText("Oops! That didn't work!");
                    }
            });

        RequestQueue queue = Volley.newRequestQueue(getApplicationContext());
        queue.add(stringRequest);
```
Running the code will give output like this:

> 2019-11-26 16:01:54.716 19105-19105/com.anta40.app.unicodetest2 I/System.out: Asma: Ø§ÙØ¥ÙÙØ·Ø§Ø±
> 2019-11-26 16:01:54.737 19105-19105/com.anta40.app.unicodetest2 I/System.out: Asma: Ø§ÙØ¥ÙØ´ÙØ§Ù
> 2019-11-26 16:01:54.769 19105-19105/com.anta40.app.unicodetest2 I/System.out: Asma: Ø§ÙØ¨Ø±ÙØ¬
> 2019-11-26 16:01:54.788 19105-19105/com.anta40.app.unicodetest2 I/System.out: Asma: Ø§ÙØ·Ø§Ø±Ù
> 2019-11-26 16:01:54.798 19105-19105/com.anta40.app.unicodetest2 I/System.out: Asma: Ø§ÙØ£Ø¹ÙÙ
> 2019-11-26 16:01:54.812 19105-19105/com.anta40.app.unicodetest2 I/System.out: Asma: 864 19105-19105/com.anta40.app.unicodetest2 I/System.out: Asma: Ø§ÙØ´Ø±Ø­
> 2019-11-26 16:01:54.875 19105-19105/com.anta40.app.unicodetest2 I/System.out: Asma: Ø§ÙØªÙÙ
> 2019-11-26 16:01:54.885 19105-19105/com.anta40.app.unicodetest2 I/System.out: Asma: Ø§ÙØ¹ÙÙ
> 2019-11-26 16:01:54.901 19105-19105/com.anta40.app.unicodetest2 I/System.out: Asma: Ø§ÙÙØ¯Ø±
> 2019-11-26 16:01:54.918 19105-19105/com.anta40.app.unicodetest2 I/System.out: Asma: Ø§ÙØ¨ÙÙØ©

This is my test repo: https://github.com/anta40/UnicodeTest2

**Comment by jpd236** [comment]
The server does not appear to be specifying a charset in the response:

content-type: application/json

As such, Volley uses the [HTTP default](https://www.w3.org/International/articles/http-charset/index#charset), ISO-8859-1. Volley is behaving correctly here. Either the server should return a content-type header that includes the charset, like:

content-type: application/json; charset=utf-8

or you will need to make a custom request which uses a different default charset when none is provided by the server.
