### ISSUE TITLE
 Failed to connect

### ISSUE THREAD

**Issue by Jerd22** [google/volley#310]
Error On android API28 Ver.9 

com.android.volley.NoConnectionError: java.net.ConnectException: Failed to connect to /172.21.43.249:8383

**Comment by jpd236** [comment]
Does it work if you just use HttpUrlConnection directly?

You're probably hitting https://github.com/google/volley/wiki/Frequently-Asked-Questions#why-are-network-requests-failing-when-i-set-targetsdkversion--28-android-p-or-higher. Please reopen if not.

**Comment by Jerd22** [comment]
I did find error on  Emulator for Android. But i  didn't find error on device for Android
