### ISSUE TITLE
Volley timeout error, while using ip address and http.

### ISSUE THREAD

**Issue by Puspharaj** [google/volley#311]
Hi,

I've using volley since it's debut. I haven't faced any issued until recent Android 28 and above the webview or any other request which loads through ip address/http which is not allowed and getting timeout error.

Is there any way i can test my application through ip address?, since i have not confirmed my FQDN to buy out domain or ssl. Initial stage of development doesn't require domain name SSL. Would you please let me know how to sort it out.

Thanks
Puspharaj

**Comment by jpd236** [comment]
Please see https://github.com/google/volley/wiki/Frequently-Asked-Questions#why-are-network-requests-failing-when-i-set-targetsdkversion--28-android-p-or-higher and let us know if that doesn't resolve your question.
