### ISSUE TITLE
Is it possible to wrap an existing socket rather than provide a URL for a request?

### ISSUE THREAD

**Issue by illumi** [google/volley#312]
As the header states really, I'd like to make a request and receive a response to a socket which I have previously opened my self. I'd also like to manage the state of the socket myself, for example, performing a request shouldn't close the socket.

**Comment by jpd236** [comment]
You can provide your own BaseHttpStack implementation which implements executeRequest:

https://github.com/google/volley/blob/master/src/main/java/com/android/volley/toolbox/BaseHttpStack.java

and handle the connections however you'd like there. Then create your request queue with Volley.newRequestQueue, providing your stack here:

https://github.com/google/volley/blob/master/src/main/java/com/android/volley/toolbox/Volley.java#L40

I think that should cover your needs, but please reopen with more details on what additional hooks you would need if this isn't enough.

**Comment by illumi** [comment]
Thanks for that JPD, I've ended up going for [https://github.com/renatoathaydes/rawhttp](RawHttp) that I can just provide an input/output stream.
