### ISSUE TITLE
Volley can not put more than one  "Set-cookie" in the response hearder at once

### ISSUE THREAD

**Issue by githubzzc** [google/volley#313]
more than one "Set-cookie" in a http response header supported by http policy.
But Volley can't support. please fix it

**Comment by uhager** [comment]
Doesn't NetworkResponse#allHeaders contain the duplicate headers? NetworkResponse#headers is the older version which returns a Map<String,String> which does not allow duplicates, while allHeaders returns a List<Header> which (as far as I can tell) should contain everything. That is, assuming you use Volley's HurlStack, which copies over all headers from the response (line 128). If you use a different stack, you'll have to do something similar there to pipe the headers back into NetworkResponse.

**Comment by jpd236** [comment]
That's right. See https://github.com/google/volley/issues/21 for details on getting access to all headers from the response. Make sure you're using the latest version of volley.
