### ISSUE TITLE
I'm having the same issue. Getting an error like this:

### ISSUE THREAD

**Issue by indian88ward** [google/volley#314]
I'm having the same issue. Getting an error like this:
`E/Volley: [19988] NetworkDispatcher.run: Unhandled exception java.lang.RuntimeException: Stub! java.lang.RuntimeException: Stub! at org.apache.http.ProtocolVersion.<init>(ProtocolVersion.java:6) at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:148) at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:97) at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:118)`

_Originally posted by @rahulupadhyay in https://github.com/google/volley/issues/235#issuecomment-433907168_

**Comment by jpd236** [comment]
Please update to Volley 1.1.1 and see if you're still encountering the same issue. The stack trace indicates that you're on an older version. HurlStack does not currently have any references to org.apache.http.
