### ISSUE TITLE
Suggest making Builder for the Request class.

### ISSUE THREAD

**Issue by kjinwoo12** [google/volley#318]
Now
```Java
StringRequest stringRequest = new StringRequest(Request.Method.GET, URL,
                (response)->{
                     blahBlahCode(response);
                },
                (error)->{
                    blahBlahCodeForError(error)
                }) {
            @Override
            public Map<String, String> getHeaders() throws AuthFailureError{
                Map<String, String> header = new HashMap<>();
                header.add("token", getToken());
                return header;
            }
        };
```
My idea.
```Java
StringRequest stringRequest = RequestBuilder.newRequest()
                        .method(Request.Method.GET)
                        .url(URL)
                        .response((response)->{
                            blahBlahCode(response);
                        })
                        .error((error)->{
                            blahBlahCodeForError(error);
                        })
                        .headers((header)-{
                            header.add("token", getToken())
                        });
```
In my opinion, making a builder class for the Request class is good idea. I think if the request has to modify something like headers or body, it makes code looks like confused. There are many changing of indent for just one constructor. If now already has similar or better solution please tell me. Thank you.

**Comment by jpd236** [comment]
Thanks for the suggestion!

You can see my thinking on this at https://github.com/google/volley/pull/206#issuecomment-403589422.  In short, I think it's an interesting idea, but would probably want to see it iterated on externally before trying to upstream it into Volley itself. The concept works fine as an external helper library. Further down on that page are a couple links to helper libraries that accomplish this:

https://github.com/naver/volley-extensions/tree/master/volleyer
https://github.com/yakivmospan/volley-request-manager

I haven't looked closely at these, but you might find them useful to simplify your code.
