### ISSUE TITLE
DiskBasedCache: pruneIfNeeded Could not delete cache entry 

### ISSUE THREAD

**Issue by baderkhane** [google/volley#320]
Hello,
I am facing a weird behavior from volley cache system, i noticed recently the news feed that we show for users still the old one (from 4 days cache). After checking my android studio logs, i saw DiskBasedCache couldn't delete cash file entry. 
I am trying to don't increase cache limit, but it will just avoid problem temporarily.
When the function **pruneIfNeeded** couldn't delete a file ? 

```
    while (iterator.hasNext()) {
        Map.Entry<String, CacheHeader> entry = iterator.next();
        CacheHeader e = entry.getValue();
        boolean deleted = getFileForKey(e.key).delete();
        if (deleted) {
            mTotalSize -= e.size;
        } else {
            VolleyLog.d(
                    "Could not delete cache entry for key=%s, filename=%s",
                    e.key, getFilenameForKey(e.key));
        }
        iterator.remove();
        prunedFiles++;
        if ((mTotalSize + neededSpace) < mMaxCacheSizeInBytes * HYSTERESIS_FACTOR) {
            break;
        }
    }
```
Thanks a lot

**Volley version: V1.1.1
Testing device: Nexus 5x  -android 8.1.0
Mode : debug**

**Comment by joebowbeer** [comment]
File.delete can fail for several reasons, such as the file no longer exists, or it is currently locked.

If the same file persists in evading trimming, then you may need to clear the cache.

**Comment by baderkhane** [comment]
@joebowbeer thanks for your answer, i was thinking whenever i catch this specific exception i will clear all the cache.

**Comment by jpd236** [comment]
Yeah, not much we can do within Volley if File#delete fails, though it seems a bit strange to me.

That said, if you're relying on pruneIfNeeded for _correctness_, then I would argue that your code is doing the wrong thing. pruneIfNeeded is meant to free up space if the cache fills up - it has nothing to do with the TTL of the data. The bug you observed is seeing stale data in the app, so relying on the behavior of "the cache should fill up frequently enough that stale data gets purged in a timely manner" is quite brittle.

The TTL of the data should be set correctly to ensure that even if the cache entries can't be deleted, the values stop being used once they have expired.
