### ISSUE TITLE
I have this volley error com.android.volley.NoConnectionError: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb9635f30: Failure in SSL library, usually a protocol error

### ISSUE THREAD

**Issue by majedalmoqbeli** [google/volley#324]
`javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb95b5e10: Failure in SSL library, usually a protocol error
    error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x83bdf770:0x00000000)`

The problem is only on android < 4.4 
my code :

`implementation 'com.android.volley:volley:1.1.1'`
_________________________________________________________

`StringRequest stringRequest = new StringRequest(Request.Method.POST, url,
                response -> {
                    
                    Log.i("Responselogin :", response);

                }, error -> {
            
            Log.i("VolleyErrorlogin :", error.toString());
            Toast.makeText(LoginActivity.this, getString(R.string.internetError), Toast.LENGTH_LONG).show();
        
		}) {
            @Override
            protected Map<String, String> getParams() {
                return map;
            }
        };
        stringRequest.setShouldCache(false);

        RequestQueue requestQueue = Volley.newRequestQueue(LoginActivity.this);
        requestQueue.add(stringRequest);`

**Comment by majedalmoqbeli** [comment]
**I fixed by using this function :** 

`private void updateAndroidSecurityProvider() {
        try {
            ProviderInstaller.installIfNeeded(this);
        } catch (Exception e) {
            e.getMessage();
        }
    }`

**Comment by Naguchennai** [comment]
Where must it be added?

**Comment by majedalmoqbeli** [comment]
> Where must it be added?

Hi @Naguchennai you can call this in your base activity.
But why your app still support android version <4.4
You can up your minSdk to support sdk 23 cuz now this is required, if you want to use the last version of firebase and some libraries.
