### ISSUE TITLE
Requests not sent and issbsettingenabled false

### ISSUE THREAD

**Issue by MrAnima** [google/volley#33]
When I try to send a request, it seems to do absolutely nothing, and the callback is never called.
It also prints this in the logcat:

I/System.out (HTTPLog)-Static: isSBSettingEnabled false
I/System.out (HTTPLog)-Static: isSBSettingEnabled false
I/qtaguid Tagging socket 36 with tag 7dbc04b800000000{2109473976,0} for uid -1, pid: 7750, getuid(): 10553
I/qtaguid Untagging socket 36

Apparently, I read that this occurs on Samsung devices, and I am indeed on a Galaxy A3. What's very strange is that this bug started at a random moment, after removing a few things from my code that have absolutely nothing to do with internet (animations). I have tried reinstalling my app, cleaning the data/cache, rebooting my phone but nothing worked.

**Comment by jpd236** [comment]
Unfortunately there's nothing actionable here from the Volley perspective. Those log messages aren't meaningful to the library itself. I would try reproducing the bug on another device or an emulator, and if it's truly specific to Samsung then the issue probably has to be raised with them. If not, please provide sample code for how to reproduce the problem and a bit more details about what it is your code is doing that is failing.

You could also try using a different HTTP stack if that's the issue.

**Comment by MrAnima** [comment]
Okay, thanks for the information, and it's Samsung-specific. I'll try rewriting this code, and see when the error re-appears.
