### ISSUE TITLE
E/Volley(4288): [562] BasicNetwork.performRequest: Unexpected response code 400 for 

### ISSUE THREAD

**Issue by wahdatjan** [google/volley#339]
I am always getting this volley error only on one device samsung Tablet but works on rest of the devices.Normal response is coming when hitting the same URL on another devices .

**Comment by jpd236** [comment]
That's a server-side error, so my recommendation would be to look at the server-side logs to understand why the request looks different from those devices and is being handled differently.

If you don't have control over the server, I would recommend trying to build the request with HttpUrlConnection directly and seeing if it behaves differently. If it doesn't work there, then it's an issue with HttpUrlConnection on the device, not Volley. If it does, then look into what Volley and HttpUrlConnection are doing differently. Let us know if you find something more specific indicating what Volley is doing inconsistently/wrong.
