### ISSUE TITLE
volley keeps showing 403

### ISSUE THREAD

**Issue by babakmuir** [google/volley#340]
volley keeps showing 403 while the url is working
JsonObjectRequest request=new JsonObjectRequest(Request.Method.GET,
                "http://api.openweathermap.org/data/2.5/weather?q=Tehran&apikey=9e387879c7f33461b013c033063a3417",
                null, new Response.Listener<JSONObject>() {

            @Override
            public void onResponse(JSONObject response) {
                onWeatherInfoRecieved.onReceived(parseResponseToWeatherInfo(response));
            }

        }, new Response.ErrorListener() {

            @Override
            public void onErrorResponse(VolleyError error) {
                onWeatherInfoRecieved.onReceived(null);
            }

        });

        request.setRetryPolicy(new DefaultRetryPolicy(20000,DefaultRetryPolicy.DEFAULT_MAX_RETRIES,DefaultRetryPolicy.DEFAULT_BACKOFF_MULT));
        RequestQueue requestQueue= Volley.newRequestQueue(context);
        requestQueue.add(request);

**Comment by jpd236** [comment]
The URL gives me a 401 when I open it in a browser.

In general, Volley is just a thin wrapper around HttpUrlConnection. It's likely there is something else different about the request you're making when it's working for you vs. when it's not. I recommend trying to get your request working with HttpUrlConnection directly to eliminate Volley as the problem, and reopen this if it works for you with HttpUrlConnection but not Volley with more details.
