### ISSUE TITLE
NetWorkDispatcher leak

### ISSUE THREAD

**Issue by qssq** [google/volley#36]
After the activity was destroyed, I called the cannel method, but listener was still leaking
[http://blog.csdn.net/wangshihui512/article/details/51249048](http://blog.csdn.net/wangshihui512/article/details/51249048)
I'm in the same position as this address, but the solution isn't good because it doesn't automatically cache offline.

**Comment by qssq** [comment]
unofficial mirror (with some minor bugfix) for volley.      compile 'com.android.volley:volley:1.0.0'  leak please fix bug

**Comment by qssq** [comment]
https://github.com/blood1093/Volley_mcxiaoke  this not bug, bug this not auto cache

**Comment by qssq** [comment]
public void cancelAll(RequestFilter filter) {
        synchronized (mCurrentRequests) {
            for (Request<?> request : mCurrentRequests) {
                if (filter.apply(request)) {
                    if (request instanceof StringRequest) {

                        ((StringRequest) request).clearListener();
                    }
                    request.cancel();
                }
            }
        }
    }

**Comment by xesam** [comment]
想在 com.android.volley:volley:1.0.0 中修正 bug 是没戏了，你只能自己手动修改然后打包了

**Comment by jpd236** [comment]
See #15
