### ISSUE TITLE
Volley - Using tool Frida memory dump, third party people can fetch requests and responses from cache.

### ISSUE THREAD

**Issue by pankajpy** [google/volley#375]
Hi Volley team,
Our QA reporting an issue that using Frida Memory Dump tools [here](https://github.com/Nightbringer21/fridump), user can fetch requests and response which was cached in app's context. Could you please help to resolve the issue or you can fix in your up coming drop?

What I tried?
1) set property `setShouldCache(false);` throughout request constructors. As well `request.setShouldCache(false):`
2) Passed invalid cache path in requestQue object, so that volley could not save cache, but issue is still reproducible.

```
            HttpStack httpClientStack = new HttpClientStack(httpClient);
            Network network = new BasicNetwork(httpClientStack);
            Cache cache = new DiskBasedCache(new File(""));
            requestQueue = new RequestQueue(cache, network);
```
3) Changed retention policy and set retry option to 0. It's because volley may persist cache for retry option, but that also could not help.

**Comment by jpd236** [comment]
Volley's requests and responses are stored in memory. How else would the application be able to read them? I don't see why the cache would have any relevance here.

Can you be more precise about why you think this is a bug and what behavior you'd expect? Do you see anything different for other HTTP libraries you've tried?

**Comment by pankajpy** [comment]
Hi @jpd236 - If you'll go through Frida tools, they dump complete application memory cache. I.e. if you you've saved preferences, or any data under app memory, they fetch as strings if it's readable.

In our case, it's username and password we're sending in request and by memory dump, we can access the complete  data saved in memory. 
Issue here is that while checking string.txt file fetch by Frida will have requests and response captured where setShouldCache(), etc even don't work and we can fetch the requests/response sent.

About Frida, here is the reference link https://github.com/rootbsd/fridump3

**Comment by jpd236** [comment]
Yes, you're going to have the contents of requests and responses in your own app's memory. This has nothing to do with caching - you need to be able to read the request and responses to be able to do anything with them in your app. Again, I wouldn't expect this to be any different from any other conventional HTTP stack.

If you can find another HTTP stack that does things differently, and can make a more concrete request as to what Volley should be doing differently, then we can reconsider. But your own application's memory is not something that we would consider an area of insecurity. Other applications on the device won't have access to it.

**Comment by pankajpy** [comment]
Hi @jpd236, I see issue closed, but having some of the doubts if you can answer please?
1) If we set retry as 0, why we should keep request or response in memory?
2) Is there anyway if we can avoid having request/response in memory? I know it's in app's memory and no other app can access, but issue raised by dumping our application memory. 
3) Different HTTP stack? you means some other libraries like OkHttp etc?

**Comment by jpd236** [comment]
1. Retries are second tries. The request and response are still kept in memory for the first try, from the time the request is started, until the time there are no outstanding references to the Request object or any copied versions of that data and the VM elects to garbage collect the data (which could be arbitrarily long after the references are gone).
2. No. Volley is designed around easy access to requests/responses in memory.
3. Yes. I suppose other HTTP stacks generally provide stream interfaces, and leave it to you to read the streams and do what you want with them. While reading the stream, the contents of responses will be in memory. You might observe them cleaned up more quickly (again, this is up to the garbage collector). But Volley is not going to make any effort to prevent requests/responses from being visible in your own app's memory.
4. It controls whether responses should be cached according to the implementation of the provided cache. In the case of DiskBasedCache, it controls whether responses should be stored on disk, so they can be read even if the app is killed and restarted.
