### ISSUE TITLE
Add licensing information for maven metadata

### ISSUE THREAD

**Issue by mpmarkburgess** [google/volley#377]
Unsure if this is the proper place to request this, but I am using [Google's OSS plugin library](https://github.com/google/play-services-plugins/tree/master/oss-licenses-plugin).  This plugin scans the maven repos for the POM file and pulls the licensing information from it to generate the information displayed in the Activity.  However, Volley currently is missing the "licenses" element in the POM and hence is excluded from the final list.

From https://repo.spring.io/libs-release/com/android/volley/volley/1.1.1/volley-1.1.1.pom:
```
<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.android.volley</groupId>
  <artifactId>volley</artifactId>
  <version>1.1.1</version>
  <packaging>aar</packaging>
</project>
```

**Comment by jpd236** [comment]
Thanks - this was identified and should be fixed with #352 and should be included in our next release.
