### ISSUE TITLE
Double-Checked Locking

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/volley#384]
https://github.com/google/volley/blob/cd0839113b100f163df1ebd04ce6d5b9e36e9863/src/main/java/com/android/volley/AsyncRequestQueue.java#L189-L193

Double-Checked Locking is widely cited and used as an efficient method for implementing lazy initialization in a multithreaded environment.
Unfortunately, it will not work reliably in a platform independent way when implemented in Java, without additional synchronization.

**Comment by jpd236** [comment]
The problems I'm aware of regarding double-checked locking in Java (which it looks like you're referencing from https://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html) impact old versions of Java (JDK4 and earlier). See the bottom of the page under "Fixing Double-Checked Locking using Volatile". To my knowledge, this does not impact Android Java. Feel free to reopen if you have evidence to the contrary.
