### ISSUE TITLE
URL called has Cache-Control with NO soft expiration, But requests still get processed as soft expires and return 2 responses.

### ISSUE THREAD

**Issue by Bradleycorn** [google/volley#388]
I'm not sure if I've found a defect or not, but here goes. 

I'm calling a url in which the resulting Cache Entry `ttl` and `softttl` are the same (i.e. the response can be/is cached, but there is no soft caching enabled).  But, in certain edge cases, if another request for the same url is sent **right** before (like a few milliseconds) the cache ttl value, it will still perform the soft caching behavior resulting in 2 responses getting delivered (one from the cache, and then a fresh response from the network moments later). 

I believe the issue is in the `CacheDispatcher.processRequest()` method. In that method, it first checks for a completely expired cache item (line 142 ... `if (entry.isExpired())`). At this point, the entry is NOT expired, so this block is (correctly) skipped.  Several lines later, it checks for a soft expiration (line 167 ... `if (!entry.refreshNeeded())`), and if there is a soft expire, then it'll deliver the cached response, and make a fresh network call and then delivery that response.  As I mentioned, in my case there is no soft caching enabled in the response headers. The `ttl` and `softttl` on the cache entry get the same value. To me, that should mean it's impossible to generate a soft expiration. But what happens is that line 142 is executed a millisecond or 2 before the expiration (so it's not expired), and then by the time it gets to line 167, a few milliseconds have gone by and it checks for a soft expiration and now the time has passed the expiration and it determines that it has indeed hit the soft expiration. 

It seems like the check for `entry.isExpired()` and `entry.refreshNeeded()` should happen at the exact same moment (same millisecond) so that the CacheDispatcher can properly handle an edge case where it's process an entry as the cache time is expiring.

**Comment by jpd236** [comment]
This seems plausible, though relatively unlikely. How often do you see this in practice? (To confirm it's in fact the cause of the problem you're seeing).

Will try to take a closer look soon. We'll probably need to do something like take a timestamp up front and use it for all ensuing staleness evaluations rather than checking for the system time multiple times, though I'm not sure whether that might require API changes.

**Comment by Bradleycorn** [comment]
We actually see it quite often. But admittedly, our use case might not be super common. We have several url's that we call in our app that are setup to be polled frequently. Some of them we call as often as every 30 seconds. Each URL has Cache Control headers to prevent polling more often than necessary. So on a url that should be polled every 30 seconds, the Cache Control header is set to expire in 30 seconds. It's these frequently polled URL's where we see the issue a lot. To your point, I think the issue is relatively unlikely. But in our case, we have thousands of users who are all calling a url every 30 seconds ... So, if the likelyhood is 1 in X, our users are generating X+n calls, and so we do see it. For example in the last 7 days our Crashlytics logs showed  that it happened 108 times. Firebase won't give me raw totals, so I have to guess at how many total calls were made, but I would guess it was in the hundreds of thousands.

I only found it because we are using Kotlin and use Coroutines for these async network calls. When volley delivers the response, we "resume" the coroutine we have setup, and we noticed crashes showing up in our logs because the coroutines were being "resumed" twice, and the Kotlin runtime would throw an exception. I finally traced it back to the issue mentioned above. I caught the exception and added some logging to get timestamps of when the request happens and the soft and hard expirations, and that confirmed it.

**Comment by jpd236** [comment]
I think #391 should fix this. Thanks for the detailed report and description. I agree if soft and final expiry are set to identical times, we shouldn't ever be triggering the soft expiry logic; either the final expiry should hit and the request should be sent over the network once without cache delivery, or it shouldn't hit and the entry should be used without a subsequent network call.

**Comment by Bradleycorn** [comment]
Awesome, thanks! To my untrained, eye, that PR does look like it will fix it.
