### ISSUE TITLE
not displaying all data from server

### ISSUE THREAD

**Issue by AashriyaTechnology** [google/volley#389]
Map<String, String> params = new HashMap<String, String>();
        gstArrayList.clear();
        ApiConfig.RequestToVolley2(new VolleyCallback() {
            @Override
            public void onSuccess(boolean result, String response) {
                **System.out.println("gst Array response" + response + result);**
                if (result) {
                    try {
                        JSONObject objectbject = new JSONObject(response);
                        int pos = 0;
                        if (!objectbject.getBoolean(Constant.ERROR)) {
                           JSONArray jsonArray = objectbject.getJSONArray(Constant.DATA);
                            **System.out.println("gst Array List " + jsonArray );**
                            **System.out.println("gst Array length= " + jsonArray.length() );**

                        }
                    } catch (JSONException e) {
                        e.printStackTrace();
                        System.out.println("gst StackTrace " + e );
                    }
                }
            }
        }, GstServiceActivity.this, Constant.GST_URL, params, true);

    }

get result as

 `I/**System.out: gst Array response**{"error":false,"data":[{"id":"1","name":"80G & 10AA Registration"},  ......      ,{"id":"55","name":"E-way Bi`   end here

and 
 `I/**System.out: gst Array List** [{"id":"1","name":"80G & 10AA Registration"},  ......   ,{"id":"55","name":"E-way Bill- Single"},{"id":"56","`  end here 

and 
`I/**System.out: gst Array length= 147**`

it all row list no. are 147 .

any one please guide me why im not get all data  .

where **ApiConfig.RequestToVolley2**

     ` public static void RequestToVolley2(final VolleyCallback callback, final Activity activity, final String url, final Map<String, 
     String> params, final boolean isprogress) {
        if (ProgressDisplay.mProgressBar != null) {
            ProgressDisplay.mProgressBar.setVisibility(View.GONE);
        }
        final ProgressDisplay progressDisplay = new ProgressDisplay(activity);
        progressDisplay.hideProgress();
        if (AppController.isConnected(activity)) {
            if (isprogress)
                progressDisplay.showProgress();
            StringRequest stringRequest = new StringRequest(Request.Method.POST, url, new Response.Listener<String>() {
                @Override
                public void onResponse(String response) {
                    callback.onSuccess(true, response);
                    if (isprogress)
                        progressDisplay.hideProgress();

                }
            },
                    new Response.ErrorListener() {
                        @Override
                        public void onErrorResponse(VolleyError error) {
                            if (isprogress)
                                progressDisplay.hideProgress();
                            callback.onSuccess(false, "");
                            String message = VolleyErrorMessage(error);
                            if (!message.equals(""))
                                Toast.makeText(activity, message, Toast.LENGTH_SHORT).show();
                        }
                    }) {

                @Override
                public Map<String, String> getHeaders() {
                    Map<String, String> params1 = new HashMap<String, String>();
                    params1.put(Constant.AUTHORIZATION, "Bearer " + createJWT("H", "H Authentication"));
                    return params1;
                }

                @Override
                protected Map<String, String> getParams() {
                    params.put(Constant.AccessKey, Constant.AccessKeyVal);
                    return params;
                }
            };

            stringRequest.setRetryPolicy(new DefaultRetryPolicy(0, DEFAULT_MAX_RETRIES, DEFAULT_BACKOFF_MULT));
            AppController.getInstance().getRequestQueue().getCache().clear();
            AppController.getInstance().addToRequestQueue(stringRequest);
        }

    }
`

**Comment by jpd236** [comment]
If you're just dumping your responses to logcat to determine if they're complete, there's a limit to the length of a string passed to logcat (about 4K); any additional text will just be truncated. Are you sure the response is _actually_ incomplete, or are you only judging via printing to System.out?

In the future, if you have general questions about how to use Volley, please use StackOverflow or our user group at volley-users@googlegroups.com. This is a forum for reporting potential bugs in Volley itself.
