### ISSUE TITLE
OutOfMemoryError when executing newRequestQueue

### ISSUE THREAD

**Issue by rosenpin** [google/volley#392]
Hi!

I'm using volley in one of my apps in production, this is an issue I can't reproduce naturally on my device.  
I am getting an OutOfMemoryError on some devices when trying to call the `newRequestQueue` function  
I made sure to only call it once in my application, this is the code of my application class

``` kotlin

class AppName : Application() {

    private var queue: RequestQueue? = null

    override fun onCreate() {
        super.onCreate()
        synchronized(AppName::class) {
            instance = this
        }
    }

    fun getRequestQueue(): RequestQueue? {
        synchronized(AppName::class) {
            queue?.let {
                return it
            }

            val newQueue = Volley.newRequestQueue(applicationContext)
            queue = newQueue
            return newQueue
        }
    }


    companion object {
        private var instance: AppName? = null
        fun getInstance(): AppName? {
            synchronized(AppName::class) {
                return instance
            }
        }
    }
}
```

And when I try to access the request queue I'm doing it using `AppName.getInstance()?.getRequestQueue()`.  
If I'm not mistaken this is the way the library should be used, and yet I got several crashes on users devices.

This is my wrapper:

``` kotlin
interface OnResponseListener {
    fun onSuccess(response: String?)
    fun onError(error: VolleyError?)
}

class Requests {
    /**
     * this will sometimes fail, in the best case it will notify the onResponse listener onError method
     * worst case it will just do nothing
     */
    fun makeRequest(url: String, onResponseListener: OnResponseListener?) {
        try {
            val application = DMMe.getInstance()
            if (application == null) {
                // seriously bad, application should never be null
                onResponseListener?.onError(VolleyError("application is null"))
                Log.e("error in requests", "application is null")
                return
            }
            val queue = application.getRequestQueue()
            val stringRequest = StringRequest(
                Request.Method.GET,
                url,
                { onResponseListener?.onSuccess(it) },
                { onResponseListener?.onError(it) })
            queue?.add(stringRequest)
        } catch (e: Exception) {
            onResponseListener?.onError(VolleyError(e.message))
        } catch (e: OutOfMemoryError) {
            // this obviously doesn't work
            onResponseListener?.onError(VolleyError(e.message))
        }
    }
}
```

I received the crashes on 2 devices until now
* Samsung Galaxy S20 FE
* Samsung Galaxy J4

This is the crash log (provided kindly by Play Console)
```
java.lang.OutOfMemoryError

java.lang.OutOfMemoryError: 
  at java.lang.Thread.nativeCreate (Thread.java)
  at java.lang.Thread.start (Thread.java:887)
  at com.android.volley.RequestQueue.start (RequestQueue.java:7)
  at com.android.volley.toolbox.Volley.newRequestQueue (Volley.java:7)
  at com.android.volley.toolbox.Volley.newRequestQueue (Volley.java:7)
  at com.android.volley.toolbox.Volley.newRequestQueue (Volley.java:7)
  at io.rosenpin.appname.utils.network.Requests.makeRequest (Requests.java:4)
  at io.rosenpin.appname.activities.MainActivity$loadBilling$1.a (MainActivity.java:13)
  at com.android.billingclient.api.zzae.run (zzae.java:4)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8414)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:596)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```

**Comment by jpd236** [comment]
I don't see anything obviously wrong in your code. Volley is hitting an OutOfMemoryError when trying to create its five threads (one cache dispatcher and four network dispatchers); that's not a particularly huge amount. So what could be happening?

- There's a memory leak / high memory usage elsewhere in the application, and Volley happens to push you over the limit in this case.
- There's a bug in these specific devices that causes them to spuriously throw OOM exceptions even when memory is available.

There's at least some signs of the possibility that Thread#nativeCreate can throw OOMs even when it makes no sense (e.g. https://github.com/AltBeacon/android-beacon-library/issues/589. But we can't really do anything about it if it does. If we can't create threads, we can't make any network requests. We'd have to put in some clunky hacks to essentially fail all network requests that get queued to avoid crashing, and/or add a retry loop, and it's unclear to me that this is better than just crashing, especially if things start working later on.

All I can really suggest is that you can try asking Volley to make fewer network dispatcher threads by using this RequestQueue constructor: https://github.com/google/volley/blob/master/src/main/java/com/android/volley/RequestQueue.java#L152. The default is 4; if you don't need that many requests in parallel, you can always drop it. Beyond that, I unfortunately think we have to close this as infeasible.

**Comment by rosenpin** [comment]
Thanks for the detailed response.
That's unfortunate, since opening this issue it happened 3 more times, so it can't be such a rare edge case since I don't have that many users.

It happened on the following devices:

- Samsung Galaxy J4
- Samsung Galaxy S10+
- Samsung Galaxy S20 FE
- Samsung Galaxy S8
- Samsung Galaxy J6

This is a little concerning since 2 of these devices have 8GB of RAM

I don't believe this is caused by a memory leak somewhere else in the application, since all of my OOM errors occurred exclusively in Volley.  
It could be a bug in the OS but I doubt that as well, the error is raised in `java.lang.Thread.nativeCreate`, it it had faulty code, why only happen when using Volley?

Anyway, I could use less threads, I use Volley for background operations that could be slower/fail so I'm down to trying that, seems like there's no exported function to use this constructor though, and initializing it manually will require me to also initialize a cache object and a Network object, perhaps it would be better to add a creator function similar to `newRequestQueue` that takes thread counts as an optional argument

**Comment by jpd236** [comment]
The fact that it's entirely happening on Samsung certainly seems like a signal that there might be something specific going on with that manufacturer, but I'm not sure. I haven't heard of any issues impacting Google apps using Volley in the same way that weren't attributable to something else. I do know that thread creation can fail in this way even when plenty of memory is available, because thread creation relies on another resource that can be exhausted, but I'm not clear on the details, and would only expect that to arise if you have many threads being created.

Ultimately, there's not a lot Volley can do if it can't create a few threads, and since we're not seeing widespread reports of this from other applications, I don't think it's likely to be an issue in the Volley side that's making it more likely to happen.

Noted regarding the newRequestQueue API inconvenience, but you can mostly copy the implementation from there to create default Cache/Network objects; it's not too complicated. I'm also not confident that a crash that occurs w/ 5 threads is any less likely to occur with 2-3.

**Comment by rosenpin** [comment]
> Noted regarding the newRequestQueue API inconvenience, but you can mostly copy the implementation from there to create default Cache/Network objects; it's not too complicated. I'm also not confident that a crash that occurs w/ 5 threads is any less likely to occur with 2-3.  

Yeah I mostly agree, but it doesn't seem like I have other options

> because thread creation relies on another resource that can be exhausted, but I'm not clear on the details, and would only expect that to arise if you have many threads being created.  

My app doesn't have many threads running at the same time, probably about 5-6 in addition to the main thread while using Volley. But on that note, what resource does it rely on? I could try looking into that.

Volley runs in conjunction with other threads on my app startup, I could try delaying its startup by a few seconds (allowing the other threads to exit first) and see if it helps

**Comment by jpd236** [comment]
> My app doesn't have many threads running at the same time, probably about 5-6 in addition to the main thread while using Volley. But on that note, what resource does it rely on? I could try looking into that.
> 

Not sure what you mean exactly by "resource". Volley is pretty self contained if you're using the default stack. It just uses a few threads for dispatching requests, direct file I/O to a directory on disk if you're using the cache, and HttpUrlConnection to perform the requests.

> Volley runs in conjunction with other threads at my app startup, I could try delaying its startup by a few seconds (allowing the other threads to exit first) and see if it helps

Some of the digging I was doing on why Thread.nativeCreate throws an OOM suggests it might be tied to happening very early in the app lifecycle, so I'd be interested in hearing if delaying things a bit helps (or just shifts the problem elsewhere).
