### ISSUE TITLE
how to check received bytes or data continuously until data received fully in volley

### ISSUE THREAD

**Issue by Hax4us** [google/volley#396]
i want to download a video and everything is working fine but what i want to do is "check received or downloaded data/video continuously until full data or video download".

Check means i want to track __how many bytes i/volley received__

is it possible ? if yes then how ?

**Comment by jpd236** [comment]
The answer depends on the underlying HTTP stack you're using. As of #328, you can extend HurlStack and override createInputStream to return a FilterInputStream which can monitor when bytes are read and dispatch callbacks along the way to the request. See HurlStackTest for an example of this. (This is not yet in an official release, so you'd need to use a SNAPSHOT build or build from source).

That said, downloading large files like videos with Volley is generally an anti-pattern. Please see https://github.com/google/volley/wiki/Frequently-Asked-Questions#why-doesnt-volley-support-large-downloadsuploads and consider using a more robust framework to avoid having to load the full file contents into memory and to support resumable downloads, for example.
