### ISSUE TITLE
Fix javadoc comments

### ISSUE THREAD

**Issue by matgallacher** [google/volley#4]
[Javadoc specs have changed](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#format) and compilation fails with the following issues with java 8

<code>
C:\Repos\Volley\volley\src\main\java\com\android\volley\toolbox\BasicNetwork.java:268: error: malformed HTML
     * Converts Headers[] to Map<String, String>.
                                ^
C:\Repos\Volley\volley\src\main\java\com\android\volley\toolbox\BasicNetwork.java:268: error: bad use of '>'
     * Converts Headers[] to Map<String, String>.
                                               ^
C:\Repos\Volley\volley\src\main\java\com\android\volley\VolleyLog.java:40: error: self-closing element not allowed
     * <br />
       ^
C:\Repos\Volley\volley\src\main\java\com\android\volley\VolleyLog.java:42: error: self-closing element not allowed
     * <br />
       ^
C:\Repos\Volley\volley\src\main\java\com\android\volley\VolleyLog.java:28: error: self-closing element not allowed
 * <p/>
   ^
C:\Repos\Volley\volley\src\main\java\com\android\volley\VolleyLog.java:29: error: self-closing element not allowed
 * to see Volley logs call:<br/>
                           ^
</code>

**Comment by jpd236** [comment]
It seems like Java 8 made Javadoc linting the default, though I don't believe the specs themselves have changed (in other words, we can just fix these and they will still make sense with older compilers).

Probably just need to use `{@code Headers[]}` and `{@code Map<String, String>}` in BasicNetwork and change the `<br />`s to `<br>`s and `<p/>`s to `<p>`s in VolleyLog. PR welcome.
