### ISSUE TITLE
AndroidHttpClient

### ISSUE THREAD

**Issue by paulsmithkc** [google/volley#404]
It appears that the old deprecated Apache HttpClient is only being used for APIs 1-8. When are you planning to move the minSdkVersion up to something more modern so these dependencies can be removed?

In July 2017 the Support Library moved its minimum supported API level up to 14. I would assume that Volley would have followed suite? See source below
https://developer.android.com/topic/libraries/support-library

![image](https://user-images.githubusercontent.com/6501079/112896440-0356f980-90a4-11eb-85fa-42cb36fb2a8f.png)

**Comment by jpd236** [comment]
Please see https://github.com/google/volley/wiki/Migrating-from-Apache-HTTP. Your app should not need to pull in Apache HTTP if you are not targeting API <= 8, regardless of what Volley is doing.

Volley is developed separately from the support libraries. We've considered increasing our API level but have not had a compelling reason to do so just yet, though we may certainly do so in the future.
