### ISSUE TITLE
HTTP/3 support

### ISSUE THREAD

**Issue by alishir** [google/volley#407]
Is there any plan to add HTTP/3 support to the volley project?

**Comment by jpd236** [comment]
That's more a question of whether the underlying HTTP stack will support HTTP/3, or whether you're using a custom stack which does. The default HurlStack uses HttpURLConnection, which doesn't support it as far as I know (and would depend on the underlying Android OS either way). But if you use the experimental asynchronous Volley implementation (https://github.com/google/volley/wiki/Asynchronous-Volley), there is a Cronet-based HTTP stack, and Cronet should support HTTP/3. You can also always create your own HTTP stack using another library that supports HTTP/3 so Volley can use that to perform requests.
