### ISSUE TITLE
R8 warning: Missing class: org.chromium.net.UrlRequest$Callback

### ISSUE THREAD

**Issue by htteng1976** [google/volley#412]
Hi, I'm getting this issue when integrating volley 1.2.0 into my project.

Add library dependency:

dependencies {
    ...
    implementation 'com.android.volley:volley:1.2.0'
}

Android Studio 4.2 buid warning:

> Task :library:minifyXXXReleaseWithR8
AGPBI: {"kind":"warning","text":"Missing class: org.chromium.net.UrlRequest$Callback","sources":[{}],"tool":"R8"}

Missing class: org.chromium.net.UrlRequest$Callback

Should I have to add google play service cronet manually?

dependencies {
    ...
    implementation 'com.android.volley:volley:1.2.0'
    implementation 'com.google.android.gms:play-services-cronet:17.0.0'
}

**Comment by jpd236** [comment]
Thanks for the report!

Is this just a build warning? If you're not explicitly opting into using the Cronet stack, you should be able to safely ignore this. The classes that are missing won't be used by other HTTP stacks, so it's fine that they're missing. If you *are* opting to use the Cronet stack, then you'd need to add a Cronet dependency (from Play Services or directly).

If this warning is a major issue, we could consider splitting out a separate :volley-cronet target from Volley itself to contain anything that depends on Cronet. But to me, this feels like a fair bit more build complexity to deal with just for a warning in the optimizer. 1.2.0 has been out for over two months and this is the first report/complaint we've gotten about this.

Will leave this open to get more input, but definitely let us know if this is actually breaking builds or if things aren't working when you omit the cronet dependency. You could also add a `-dontwarn org.chromium.**` to your Proguard config to silence the warning, I think (though you would have to watch out for legitimate issues elsewhere).

**Comment by htteng1976** [comment]
Thanks for the quick reply.

It's just a build warning and didn't cause any build break. I will try your recommendataion to silence this warning. Very appreciated.

**Comment by jpd236** [comment]
Seems that there are other complaints about this from an SDK which depends on Volley, and an SDK can't reasonably disable warnings for such a broad package. So we'll have to look into separating out the -cronet artifact into its own library so apps/libraries depending on Volley alone don't run into issues.

**Comment by jpd236** [comment]
This should be resolved in the next release. Would be great if you or someone who was seeing this issue could verify that it is fixed by configuring [prerelease versions of Volley](https://github.com/google/volley/wiki/Frequently-Asked-Questions#how-can-i-use-prerelease-versions-of-volley) and seeing if 1.2.1-SNAPSHOT fixes the problem.
