### ISSUE TITLE
Bug: docs say latest version is 1.1.1, but it's 1.2.0

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/volley#416]
Here:
https://developer.android.com/training/volley

    implementation("com.android.volley:volley:1.1.1")

**Comment by jpd236** [comment]
Thanks - looks like this was introduced when the Kotlin snippet was added (the Groovy one is fine). Will have this fixed shortly.

**Comment by AndroidDeveloperLB** [comment]
@jpd236 Actually when using some dependency that uses it, it didn't say about a newer version (and it's Groovy):

https://issuetracker.google.com/issues/191810494

No idea why what I wrote was marked as a duplicate.

**Comment by jpd236** [comment]
I'm not sure how that bug relates to the docs. Gradle doesn't generally warn you if a newer version of a library is available when you are using a library that depends on an older version (and the doc has no bearing on that) - this is an issue/behavior of Gradle, not Volley.

The issue you're seemingly running into is that you want to use the places SDK, which depends on an older version of Volley that isn't available on Maven Central. That is a legitimate issue being tracked by https://issuetracker.google.com/issues/179604852 - the library should bump its dependency to a newer version of Volley. Until then, you can work around this by explicitly specifying a dependency on Volley 1.2.0 in your own application, which will override the dependency specified by the places SDK.

**Comment by jpd236** [comment]
The doc update appears to be live now.

**Comment by AndroidDeveloperLB** [comment]
@jpd236 No, it's not:
https://developers.google.com/maps/documentation/places/android-sdk/client-migration#install_the_client_library

There is no mention that I should add Volley there, let alone the new version.

**Comment by jpd236** [comment]
I was only looking at https://developer.android.com/training/volley as originally reported. That documentation is owned by a different project (the Places SDK), so I think your best bet will be to make a request to that team to see if they'd like to update the doc accordingly before the library itself can be fixed.

**Comment by AndroidDeveloperLB** [comment]
@jpd236 When reported, it was marked as a duplicate, and even though here it was handled quite quickly, there it was created much before of my post.
