### ISSUE TITLE
a question about thecode that used volley lib

### ISSUE THREAD

**Issue by alira1377** [google/volley#42]
Hello i have few questions about below code ,  i think about it very much but i can't to understand it, please help me:
`public class AppController extends Application {

    public static final String TAG = AppController.class
            .getSimpleName();

    private static RequestQueue mRequestQueue;

    private static AppController mInstance;

    public RequestQueue getRequestQueue() {
        if (mRequestQueue == null) {
            mRequestQueue = Volley.newRequestQueue(getApplicationContext());
        }

        return mRequestQueue;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        mInstance = this;
    }

    public static synchronized AppController getInstance() {
        return mInstance;
    }

    public <T> void addToRequestQueue(Request<T> req, String tag) {
        // set the default tag if tag is empty
        req.setTag(TextUtils.isEmpty(tag) ? TAG : tag);
        getRequestQueue().add(req);
    }

    public void addToRequestQueue(Request req) {
        getRequestQueue().add(req);
    }

    public void cancelPendingRequests(Object tag) {
        if (mRequestQueue != null) {
            mRequestQueue.cancelAll(tag);
        }
    }
`
why i initialize mInstance = this in oncreate method?

**Comment by jpd236** [comment]
If you have questions about code or how to use Volley, I would suggest another venue (like volley-users@ or StackOverflow, perhaps). This is an issue tracker to report bugs with Volley.
