### ISSUE TITLE
How to find the code before 1.0.0, I haven't found it after looking for it for a long time

### ISSUE THREAD

**Issue by creativityingenuity** [google/volley#426]
How to find the code before 1.0.0, I haven't found it after looking for it for a long time

**Comment by jpd236** [comment]
Nearly all of the available history is in this GitHub repository, as imported from the frameworks/volley AOSP project.

There are a handful of commits made before the oldest commit in this project (https://github.com/google/volley/commit/d56b88ae161057e848e7410d1b9ce5b0b8c427fc) from back when Volley was part of the frameworks/support AOSP project. Those commits are available here:

https://android.googlesource.com/platform/frameworks/support/+/53fd96027e9fb41019a63ca8daa5bcd664d6f244/volley/

**Comment by creativityingenuity** [comment]
> Nearly all of the available history is in this GitHub repository, as imported from the frameworks/volley AOSP project.
> 
> There are a handful of commits made before the oldest commit in this project ([d56b88a](https://github.com/google/volley/commit/d56b88ae161057e848e7410d1b9ce5b0b8c427fc)) from back when Volley was part of the frameworks/support AOSP project. Those commits are available here:
> 
> https://android.googlesource.com/platform/frameworks/support/+/53fd96027e9fb41019a63ca8daa5bcd664d6f244/volley/

![image](https://user-images.githubusercontent.com/12170093/130747344-2dd0d7e7-911b-4a71-9ebc-51356ae9a50a.png)
I found the volley we used through git records. Do you know which version of volley is the place selected in the red box?
