### ISSUE TITLE
E/Volley: [18667] NetworkUtility.shouldRetryException: Unexpected response code 403 

### ISSUE THREAD

**Issue by AndroidTutorialsyt** [google/volley#439]
E/Volley: [18667] NetworkUtility.shouldRetryException: Unexpected response code 403 for https://blogger.googleapis.com/v3/blogs/7840551652406085708/posts?key=AIzaSyAxxxxxxxxxxxxxxxxxxxzuo3gxxXW2I
W/System.err: com.android.volley.AuthFailureError
W/System.err:     at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:189)
W/System.err:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
W/System.err:     at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
W/System.err:     at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
W/System.err:     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

Help me what is error

**Comment by jpd236** [comment]
The error is that the server is returning a 403 in response to the request. You would almost certainly see the same problem with any HTTP library, or using HttpURLConnection directly. I would recommend looking into it from the perspective of the server/API you are using (looks like the Blogger API) and/or seeking help from a more general help form, as it does not appear to me that there is likely to be a Volley bug here.

If you can reproduce an issue with Volley but not HttpURLConnection, feel free to reopen with more details and we can take a closer look.
