### ISSUE TITLE
Handle http 3xx redirects out of the box

### ISSUE THREAD

**Issue by iyosifov** [google/volley#460]
https://github.com/google/volley/blame/master/core/src/main/java/com/android/volley/toolbox/NetworkUtility.java#L198

It appears that http 3xx redirects are not handled, rather they're returned as ServerError to the calling code. 
Based on the comment, this is intentional, but is there a good reason? Seems the redirect should just be followed instead. 

Found this during internal testing of changes to a rest end point and an attempt to make it return a 3xx redirect for compatibility with old clients in the field.

**Comment by jpd236** [comment]
This logic actually serves a slightly different purpose - whether to allow the request to be retried as is in the event of a failure. If a 3xx response reaches this point, there's no reason to expect that subsequent requests _to the same URI_ would have a different result.

Volley delegates the responsibility of following 3xx redirects down to the underlying HTTP stack. For example, if an app is using the default HurlStack, calling [`HttpURLConnection.setFollowRedirects(true)`](https://developer.android.com/reference/java/net/HttpURLConnection#setFollowRedirects(boolean)) should cause it to follow redirects internally, which means 3xx responses would never actually reach Volley's higher-level logic. This can also be done on a per-request basis without impacting the rest of the app by overriding [`HurlStack#createConnection`](https://github.com/google/volley/blob/master/core/src/main/java/com/android/volley/toolbox/HurlStack.java#L196) and calling `setInstanceFollowRedirects` on the connection that `super(url)` returns.

**Comment by jpd236** [comment]
I suspect this is just tied to the behavior of HttpURLConnection rather than something specific to Volley.

For example, I believe it won't follow redirects if the protocol changes (e.g. from HTTP to HTTPS or vice versa) or if the redirect URL is malformed.
