### ISSUE TITLE
jCenter is deprecated, unable to fetch the dependency

### ISSUE THREAD

**Issue by SurajValluru** [google/volley#461]
I have mavenCentral() repo added along with jcenter, I'm unable to fetch the nachos since this month Aug 15

**Comment by jpd236** [comment]
Volley is present in mavenCentral:

https://central.sonatype.com/artifact/com.android.volley/volley

and it declares no dependencies of its own. You can also use the google() repository if preferred.

AFAIK you should just remove jcenter.

I'm not aware of any issues here, but if you are unable to depend with Volley, please provide more details on the error message you're seeing, and ideally a sample project demonstrating the problem.

**Comment by SurajValluru** [comment]
I'm trying to fetch 1.1.1, that was the issue as I can see this version is not present. Will update
