### ISSUE TITLE
RecyclerView Header and Items from two separate Volley requests...

### ISSUE THREAD

**Issue by scheung38** [google/volley#53]
I have a RecyclerView with HEADER and ITEM to be populated from two separate URL JSON responses, how to approach this:

https://github.com/trangho214/HeaderToRecyclerView/blob/master/MultipleViewInRecycleView/app/src/main/java/paxcreation/com/multipleviewinrecycleview/MainActivity.java

but this is only for dummy data.

Or is this possible to embed a Volley request inside of another Volley request so that

adapter = new SimpleItemRecyclerViewAdapter(resHeader, resultItems);

are ready to be processed

Thanks

**Comment by jpd236** [comment]
If you have questions about code or how to use Volley, I would suggest another venue (like the volley-users Google Group or StackOverflow, perhaps). This is an issue tracker to report bugs with Volley.
