### ISSUE TITLE
Which is best lib. to use ?

### ISSUE THREAD

**Issue by patelakshay13890** [google/volley#58]
In my app RESTful services are called in background threading & in 1 sec i want tom kae 2 to 4 request in one thread…And there may be 3 to 4 such thread running in parallel & making individual REST request…
So in this Situation which lib. should I use ??
Plz help me out..
Thanks…

**Comment by jpd236** [comment]
If you have questions about code or how to use Volley, I would suggest another venue (like the volley-users Google Group or StackOverflow, perhaps). This is an issue tracker to report bugs with Volley.
