### ISSUE TITLE
Does volley Support HTTP/2

### ISSUE THREAD

**Issue by stillie** [google/volley#6]
Does/Will Volley support the protocol HTTP/2

**Comment by jpd236** [comment]
There's some discussion on this in the [user group](https://groups.google.com/d/topic/volley-users/dKkQdtp7hNI/discussion), but will copy my response here for posterity:

It's up to the implementation of HttpStack that you choose to use. If your stack supports HTTP 2.0 then Volley itself should have no trouble with it.

Foe example, there are a fair number of implementations of HttpStack atop OkHttp floating around that would likely work. Or, on recent versions of Android, HttpUrlConnection is backed by OkHttp, which suggests that you might just be able to use the built-in HurlStack if you only care about those platform versions, though I'm not deeply familiar with which versions would be expected to work (if any).

(Not endorsing OkHttp specifically vs. any other solution - it just happens to be the only library I'm familiar with which supports HTTP 2.0.)

**Comment by Sheikh-Aman** [comment]
For anybody who reads this and thinks of using OkHttp with Volley : OkHttp supports HTTP2 from v3.9.0 and above, but one of it's [bugs](https://github.com/square/okhttp/issues/607) keeps it from multiplexing the requests one one single connection, even on v3.11.x (which is the latest)
