### ISSUE TITLE
Unhandled exception: NullPointerException/NegativeArrayException in CacheDispatcher

### ISSUE THREAD

**Issue by hanspeteroliver** [google/volley#72]
java.lang.NegativeArraySizeException: -557
	at com.android.volley.toolbox.DiskBasedCache.streamToBytes(DiskBasedCache.java:323)
	at com.android.volley.toolbox.DiskBasedCache.get(DiskBasedCache.java:119)
	at com.android.volley.CacheDispatcher.run(CacheDispatcher.java:100)

This is my stacktrace. I think it's caused by unhandled NullPointer in the CacheDispatcher. My app crashs with this stacktrace everytime when the OS cleans up the Volley cache.

**Comment by joebowbeer** [comment]
This is a dup of Issue #12 ? (The fix for which is available in a snapshot.)

Can you explain the NullPointerException hypothesis?

**Comment by hanspeteroliver** [comment]
Yes, but I really don’t get how to fix this bug. Because I have it right now and in issue #12 I read something about 2013 and I wasn’t able to find a solution there.
The NullPointerException was from another mistake by me, I mixed it up

Von: Joe Bowbeer<mailto:notifications@github.com>
Gesendet: Sonntag, 13. August 2017 18:28
An: google/volley<mailto:volley@noreply.github.com>
Cc: hanspeteroliver<mailto:krause.oliver@outlook.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [google/volley] Unhandled exception: NullPointerException/NegativeArrayException in CacheDispatcher (#72)


This is a dup of Issue #12<https://github.com/google/volley/issues/12> ? (The fix for which is available in a snapshot.)

Can you explain the NullPointerException hypothesis?

**Comment by jpd236** [comment]
The bug was only fixed recently in the official repository. It has not made it to a public release yet but should soon.

In the mean time you can use a SNAPSHOT build of Volley if you'd like to pick up the latest bug fixes prior to the next release. There are some instructions here: https://github.com/google/volley/issues/11#issuecomment-314296577
