### ISSUE TITLE
HurlStack support streaming request body from local file

### ISSUE THREAD

**Issue by CapnSpellcheck** [google/volley#74]
For the uploading of large files, it would be nice to have a mechanism within Volley to receive body as InputStream or maybe just file (since you can create IS from that and then also determine body size).

It currently seems impossible to insert this behavior, without changing volley source.

**Comment by jpd236** [comment]
This kind of thing is against the spirit of Volley, which is that requests and responses be small enough to fit in memory. Moreover, the API structure requires that getBody() return a byte[] and so we couldn't make any changes here without breaking the API. If the request is so big that you would want to stream it, I think you're better off using a different library that is intended for large file uploads. (Volley doesn't handle things like interrupted uploads well, for example, which seems critical if you're trying to upload large files from a mobile device where connectivity can break at any time).
