### ISSUE TITLE
onErrorResponse: com.android.volley.ParseError: org.json.JSONException: Value <br of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by Wowgreat** [google/volley#78]
I use volley parse a json that I get from service by post method，but I get that problem ：onErrorResponse: com.android.volley.ParseError: org.json.JSONException: Value <br of type java.lang.String cannot be converted to JSONObject；
But I use get method  every thing is ok

**Comment by jpd236** [comment]
Sounds like your server is returning HTML and not JSON when you post to it. I recommend dumping the response as a string and seeing what it says; it's likely an error.

Please note that this is a bugtracker for Volley. If you just have questions about how to use the library, I recommend another venue like StackOverflow or the Volley-users Google Group before reporting issues here.
