### ISSUE TITLE
anonymous listener of Response causing memory leak

### ISSUE THREAD

**Issue by Hardik-mehta** [google/volley#81]
I am using Leakcanary for detecting memory leak in my app. but astonishingly leak canary reported memory leak in volley due to use of anonymous listener. I have asked this issue on StackOverflow below is the link:

anonymous-listener-of-volley-request-causing-memory-leak

**Comment by jpd236** [comment]
Please see https://github.com/google/volley/issues/15 for more discussion on this leak.

**Comment by Dayanand515** [comment]
Still getting memory leak in volley:1.1.0-rc1
I am using custom api request and have followed https://github.com/google/volley/commit/95f64de9bfa2ee44d6cf93a6dc4b980e5ec56f6a adding lock properly.
Still my response listener is leaked.
* GC ROOT com.android.volley.NetworkDispatcher.<Java Local>
* references com.oyo.consumer.network.ApiRequest.mListener

**Comment by jpd236** [comment]
Would recommend filing a new issue with more details:

- Do you have sample code?
- Are you actually cancelling the request? 
- What platform version / device?

**Comment by jpd236** [comment]
Note also: NetworkDispatcher may still hold a reference to your Request object after it is canceled - that is unavoidable. You need to cancel your requests whenever the parent context (i.e. activity) goes out of scope, and your Request needs to drop the reference to the listener in cancel(), to avoid a leak.
