### ISSUE TITLE
java.io.IOException

### ISSUE THREAD

**Issue by hariomdgr3** [google/volley#82]
if i'm frequently send a multiple request then i got an exception

java.io.IOException: unexpected end of stream on Connection{appwear.lotzap.com:80, proxy=DIRECT hostAddress=43.255.154.32 cipherSuite=none protocol=http/1.1} (recycle count=0)

--

**Comment by jpd236** [comment]
That error seems to come from the underlying HTTP stack rather than Volley, so I don't think it's likely there is a Volley bug here. More likely an issue with the server terminating the connection or the device not able to handle the traffic you're trying to send from it.
