### ISSUE TITLE
Network requests not working on Android 7

### ISSUE THREAD

**Issue by amiga** [google/volley#83]
My client is reporting that on Android 7 the network request come back as null after logging in. I really cannot understand whats going on, is there something about Android 7 that makes volley stop working? Some sort of SSL issue maybe?

**Comment by jpd236** [comment]
There's no real action that we can take here.

Volley is just an API wrapper around an underlying http stack. Have you tried reproducing the issue using that stack directly to eliminate Volley from the equation? (i.e. make requests with HttpUrlConnection or Apache HTTP directly depending on which stack you're using). It seems unlikely this is a Volley issue.

If you can reproduce this with Volley and not the underlying HTTP stack then please provide more details and ideally sample code.

**Comment by amiga** [comment]
Hey I managed to fix it using this code:

`  HurlStack hurlStack = new HurlStack() {
                @Override
                protected HttpURLConnection createConnection(URL url) throws IOException {
                    HttpsURLConnection httpsURLConnection = (HttpsURLConnection) super.createConnection(url);
                    try {
                        _("USE_SSL_HACK createConnection ->"+url.toString());
                        httpsURLConnection.setSSLSocketFactory(getSSLSocketFactory(c));
                        httpsURLConnection.setHostnameVerifier(getHostnameVerifier());
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    return httpsURLConnection;
                }
            };
            queue = Volley.newRequestQueue(c,hurlStack);

 ///SSL HACK CODE////

    // Let's assume your server app is hosting inside a server machine
    // which has a server certificate in which "Issued to" is "localhost",for example.
    // Then, inside verify method you can verify "localhost".
    // If not, you can temporarily return true
    private HostnameVerifier getHostnameVerifier() {
        return new HostnameVerifier() {
            @Override
            public boolean verify(String hostname, SSLSession session) {
                //return true; // verify always returns true, which could cause insecure network traffic due to trusting TLS/SSL server certificates for wrong hostnames
                HostnameVerifier hv = HttpsURLConnection.getDefaultHostnameVerifier();


                _("VERIFY LOCALHOST? hostname: "+hostname+" session: "+session);
                boolean verify = hv.verify(myHost, session);
                _("verify? "+verify);
                return verify;
            }
        };
    }

    private TrustManager[] getWrappedTrustManagers(TrustManager[] trustManagers) {
        final X509TrustManager originalTrustManager = (X509TrustManager) trustManagers[0];
        return new TrustManager[]{
                new X509TrustManager() {
                    public X509Certificate[] getAcceptedIssuers() {
                        return originalTrustManager.getAcceptedIssuers();
                    }

                    public void checkClientTrusted(X509Certificate[] certs, String authType) {
                        try {
                            if (certs != null && certs.length > 0){
                                certs[0].checkValidity();
                            } else {
                                originalTrustManager.checkClientTrusted(certs, authType);
                            }
                        } catch (CertificateException e) {
                            Log.w("checkClientTrusted", e.toString());
                        }
                    }

                    public void checkServerTrusted(X509Certificate[] certs, String authType) {
                        try {
                            if (certs != null && certs.length > 0){
                                certs[0].checkValidity();
                            } else {
                                originalTrustManager.checkServerTrusted(certs, authType);
                            }
                        } catch (CertificateException e) {
                            Log.w("checkServerTrusted", e.toString());
                        }
                    }
                }
        };
    }

    private SSLSocketFactory getSSLSocketFactory(Context c)
            throws CertificateException, KeyStoreException, IOException, NoSuchAlgorithmException, KeyManagementException {
        _("getSSLSocketFactory");
        CertificateFactory cf = CertificateFactory.getInstance("X.509");
        InputStream caInput = c.getResources().openRawResource(R.raw.certificate); // this cert file stored in \app\src\main\res\raw folder path

        Certificate ca = cf.generateCertificate(caInput);
        caInput.close();

        KeyStore keyStore = KeyStore.getInstance("BKS");
        keyStore.load(null, null);
        keyStore.setCertificateEntry("ca", ca);

        String tmfAlgorithm = TrustManagerFactory.getDefaultAlgorithm();
        TrustManagerFactory tmf = TrustManagerFactory.getInstance(tmfAlgorithm);
        tmf.init(keyStore);

        TrustManager[] wrappedTrustManagers = getWrappedTrustManagers(tmf.getTrustManagers());

        SSLContext sslContext = SSLContext.getInstance("TLS");
        sslContext.init(null, wrappedTrustManagers, null);

        return sslContext.getSocketFactory();
    }

    /////////////////////
`
