### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by haseebab** [google/volley#87]
I keep getting this error, even after I'm setting `setShouldCache(false)` for all my volley requests.

The error stack is:

`java.lang.OutOfMemoryError: 
  at com.android.volley.toolbox.DiskBasedCache.streamToBytes (DiskBasedCache.java:323)
  at com.android.volley.toolbox.DiskBasedCache.readString (DiskBasedCache.java:541)
  at com.android.volley.toolbox.DiskBasedCache.readStringStringMap (DiskBasedCache.java:564)
  at com.android.volley.toolbox.DiskBasedCache$CacheHeader.readHeader (DiskBasedCache.java:404)
  at com.android.volley.toolbox.DiskBasedCache.initialize (DiskBasedCache.java:157)
  at com.android.volley.CacheDispatcher.run (CacheDispatcher.java:84)`

Before I add the request to the queue this is what I do:

`JsonObjectRequest jsObjRequest = new JsonObjectRequest {...}`
`jsObjRequest.setShouldCache(false);`
`queue.getCache().clear();`
`queue.add(jsObjRequest);`

I can't figure out why I keep getting this error in production. I can't seem to replicate it in my local environment. The amount of data being returned is literally one integer. The only unique context about this code is that it runs in a Runnable task every 5 minutes.

Any input would be greatly appreciated.

**Comment by joebowbeer** [comment]
This is dup of Issue #12

**Comment by haseebab** [comment]
Thanks @joebowbeer 

I didn't realize the fix was in a snapshot. I'm trying out the latest snapshot now:

`maven { url 'https://oss.jfrog.org/artifactory/oss-snapshot-local/' }`
`compile 'com.android.volley:volley:1.0.1-SNAPSHOT'`

**Comment by haseebab** [comment]
With the above Snapshot, Android Studio is not able to find the Volley package anymore.

**Comment by jpd236** [comment]
The latest snapshot at https://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/volley/volley/1.0.1-SNAPSHOT/volley-1.0.1-20170808.194910-9.aar does seem to have a valid classes.jar inside so I think the repository is valid. Did you put the maven{} section in a repositories {} stanza and and the compile dependency inside an dependencies {} stanza?

**Comment by haseebab** [comment]
Yes. This is what I have:

`repositories {
    maven { url 'https://oss.jfrog.org/artifactory/oss-snapshot-local/' }
}`

`dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:design:25.0.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-beta4'
    testCompile 'junit:junit:4.12'

    compile 'com.android.volley:volley:1.0.1-SNAPSHOT'
}`

**Comment by jpd236** [comment]
Thanks. Something does seem to be up here - filed https://github.com/google/volley/issues/88 to look further into what's going on. In the mean time pulling the .aar file does seem to work.

**Comment by jpd236** [comment]
Other bug is fixed, so you should be able to try again. If it doesn't work, please comment on #88 with more details - thanks for the report!
