### ISSUE TITLE
SNAPSHOT builds don't seem to work

### ISSUE THREAD

**Issue by jpd236** [google/volley#88]
Pulling in com.android.volley:volley:1.0.1-SNAPSHOT from https://oss.jfrog.org/artifactory/oss-snapshot-local/ doesn't seem to work - the dep is resolved (changing to a fake version fails w/ a different error), but the Java classes aren't available to compile against.

The .aar is fine as I can pull it from the snapshot server and depend on it directly.

**Comment by jpd236** [comment]
Verified in volley-1.0.1-20170912.025418-12 (and 1.0.1-SNAPSHOT works as well).

**Comment by haseebab** [comment]
1.0.1-SNAPSHOT still doesn't seem to work for me. (The dependency resolves successfully, but Android Studio can't find the Volley package. 

Can you guide me how to compile volley-1.0.1-20170912.025418-12.aar directly. I tried putting that in my app/libs directory and adding the following to my dependencies {} stanza: 
`compile fileTree(dir: 'libs', include: ['*.jar'])`

But that doesn't seem to work.

**Comment by joebowbeer** [comment]
Clearing cache on Android Studio may be appropriate here.

**Comment by jpd236** [comment]
Yeah, try Build -> Rebuild Project or doing a command line build using gradle.

Below is a small sample project built against the 1.0.1-SNAPSHOT as proof that it's working (verified with "./gradlew app:assembleDebug" from the root of the unpacked VolleyExample directory).

[VolleyExample.zip](https://github.com/google/volley/files/1297660/VolleyExample.zip)
