### ISSUE TITLE
Cancelling Custom String Request

### ISSUE THREAD

**Issue by abdullahjhussein** [google/volley#90]
Hello there,
I have  a problem with cancel Custom String Request in Volley.
I have 2 tabs and each tab event has Volley request, so when click on tabs rapidly the two volley request are run, so need to cancel one and run the other request.

i use {App.getInstance().addToRequestQueue(customRequest, TAG);} to assign tag to request, and

i use {mRequestQueue.cancelAll(TAG);} to cancel but not work with me.

Thanks a lot.

**Comment by jpd236** [comment]
Could you elaborate on what not working means in this case? Do you have a standalone sample project that reproduces the issue?

"addToRequestQueue" is not a Volley method, so I don't know what it's actually doing.

Please also note that cancel won't actually cancel an in-flight request in terms of whether it hits the backend. All it does is prevent the response callbacks from being triggered after the request completes.

Feel free to reopen with more details if you still suspect a Volley bug.
